### ISSUE TITLE
ADD user profile & authentication 

### ISSUE THREAD

**Issue by agxmbedi** [EternoSeeker/gameoflife#10]
I am Agamjot singh. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by EternoSeeker** [comment]
I would like to know how you would do that, in detail like
- What database would be used ( preferably MongoDB )
- What data about user you'll store there
- If we are going to use node or do it in plain js or any other related library
You can start working on it after that, keep me updated, thank you.

**Comment by agxmbedi** [comment]
thank you

**Comment by codebreaker3008** [comment]
Could you assign me this ?
@EternoSeeker
