### ISSUE TITLE
Feat: Ability to change the grid size

### ISSUE THREAD

**Issue by TiwariRahul16** [EternoSeeker/gameoflife#103]
### Describe the feature

Hii @EternoSeeker

Describe the feature

Give users the ability to increase the number of rows and columns i.e. the size of the universe before starting. In case, it is to big to fit on screen.

 I have  added the functionality in which the user can change the size of grid accrording to their preference.
 I replied to issue #63 and am bringing it up once more.
 please assign this task to me.

### Add ScreenShots

Before
![before](https://github.com/EternoSeeker/gameoflife/assets/168175850/c1832881-8007-455d-a503-21ecc7fcf1b5)

After
![after](https://github.com/EternoSeeker/gameoflife/assets/168175850/8ace0267-c815-4da2-b240-a71d937e0913)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TiwariRahul16** [comment]
please assign this to me in this issue or in issue number #63

**Comment by EternoSeeker** [comment]
@TiwariRahul16 thank you for bringing it up again, can the UI for the custom grid size be better ?

**Comment by TiwariRahul16** [comment]
Thank you for assigning me, and I'll do my best. 
Would you kindly assign me #63 as well?

**Comment by TiwariRahul16** [comment]
Hi @EternoSeeker 
I've also figured out this problem.
Would you kindly assign me #97 as well?

**Comment by EternoSeeker** [comment]
I'll assign you those issues if they don't reply soon
