### ISSUE TITLE
Sidebar issue in Mobile device 

### ISSUE THREAD

**Issue by rko0211** [EternoSeeker/gameoflife#105]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![navbar_issue](https://github.com/EternoSeeker/gameoflife/assets/97402824/1974c463-c3f3-4892-82f4-e447124a4442)

When we see the website in small device sidebar are not align properly . Please assign me this task under GSSOC24 , thank you

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
#97

**Comment by EternoSeeker** [comment]
#97 is closed, and fixed
