### ISSUE TITLE
Fix the Radios & Checkboxes

### ISSUE THREAD

**Issue by Karthikeyan1508** [EternoSeeker/gameoflife#11]
## I'm submitting a ...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

## Current behaviour
The Checkboxes being restricted to the element and not to the label.

## What is the motivation / use case for changing the behavior?
I would like to change the UI of the radio & check boxes making it more easy for players (without changing the aesthetics of the website). Could you please assign me to add this feature under GSSoC'24 label ?

**Comment by Aleena-Memon** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'24.

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by juniorcoder02** [comment]
I'm excited about contributing to game of life and would love to take a shot at tackling this issue and want to change radios and checkboxes. Could you please assign it to me? Looking forward to diving in!

**Comment by raghvendra-official** [comment]
I want to work on this issue, Please assign this issue to me under GSSoC'24.

**Comment by Paavni-Goyal** [comment]
Hey, I would like to work on the same. Can you please assign this to me under GSSoC'24.

**Comment by satyaveni299** [comment]
Can you assign me this to me under GSSoC'24.

**Comment by EternoSeeker** [comment]
@Karthikeyan1508 any updates ?

**Comment by EternoSeeker** [comment]
@Aleena-Memon you can work on it
