### ISSUE TITLE
BUG: Randomness scroller is not smooth

### ISSUE THREAD

**Issue by kritiarora2003** [EternoSeeker/gameoflife#112]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I noticed that the randomness scroller is not too smooth and is sometimes incrementing in intervals of 4, sometimes not moving at all. I would like to work on correcting this. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Sure you can work on it @kritiarora2003

**Comment by S-i-y-a-g** [comment]
please assign me this issue

**Comment by EternoSeeker** [comment]
@kritiarora2003 any updates ?

**Comment by kritiarora2003** [comment]
When I checked it was working in windows but was not working on my browser in linux, so i digged deeper regarding the issue, but later it came out to be the browsers fault not the code. 
I sincerely apologise for the inconvenience. We may close this issue.

**Comment by EternoSeeker** [comment]
okay
