### ISSUE TITLE
BUG: History Button is not working

### ISSUE THREAD

**Issue by Janani-m17** [EternoSeeker/gameoflife#113]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/EternoSeeker/gameoflife/assets/124059957/351366bd-8f13-45e4-a6e7-fbf74e23b2da)
The history button is not responding. If the user clicked the history button it should render a history about the game and information about it.

@EternoSeeker 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
@Janani-m17 it is working
History section stores the pattern after you have played
So if you drew a pattern and clicked play button, the pattern gets stored in session storage as history
It stores up to 5 patterns of user in that session
