### ISSUE TITLE
BUG: Hamburger menu not opening in mobile view

### ISSUE THREAD

**Issue by karthickkumarsm** [EternoSeeker/gameoflife#114]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The hambuger menu was not working in mobile view

https://github.com/EternoSeeker/gameoflife/assets/89688112/4d85801e-a59f-42e6-b109-81487744b99f

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by TiwariRahul16** [comment]
Yes the side navbar is not working in mobile view.  
 I am working on this,
@EternoSeeker would you please assign this task to me
with suitable labels.

**Comment by karthickkumarsm** [comment]
> ### Is there an existing issue for this?
> * [x]  I have searched the existing issues
> 
> ### What happened?
> The hambuger menu was not working in mobile view
> 
>  Conway.s.Game.of.Life.and.3.more.pages.-.Personal.-.Microsoft.Edge.2024-05-23.16-10-26.mp4 
> ### Record
> * [x]  I agree to follow this project's Code of Conduct
> * [x]  I'm a GSSOC'24 contributor
> * [x]  I want to work on this issue

Kindly assign this issue to me

**Comment by EternoSeeker** [comment]
#97 2 hamburger issue was fixed here, if you have any other changes/suggestions, please tell @karthickkumarsm

**Comment by karthickkumarsm** [comment]
> #97 2 hamburger issue was fixed here, if you have any other changes/suggestions, please tell @karthickkumarsm

sure
