### ISSUE TITLE
Auto comment on an issue and self assign the issue 

### ISSUE THREAD

**Issue by MohanRamSridhar** [EternoSeeker/gameoflife#115]
## I'm submitting a ...

- [ ] Bug report
- [X] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

## What is the motivation / use case for changing the behavior?

I'll create a workflow which will auto comment on an issue and will also self assign the issue to the one who has raised it. This makes the work of the project admin easy.

**Comment by EternoSeeker** [comment]
Yes you can work on it, also auto commenting on issues is present. You can modify the text if required
Also auto assigning will be useful, thank you
