### ISSUE TITLE
[BUG]: On the media query hit, the sidemenu is getting on the top side, instead it should be in the hamburger icon which on clicking gets to the right and left.

### ISSUE THREAD

**Issue by mohit-bhandari45** [EternoSeeker/gameoflife#12]
- [x] Bug report
- [ ] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

Current behaviour:- The menu is getting on the top.

Screenshots:-
![image](https://github.com/EternoSeeker/gameoflife/assets/151373021/406333b7-635e-4dc7-9f99-7e4b086cee46)

Steps to reproduce:- 
Step 1:- Go through the app
Step 2:- just inspect and check the mobile view.

What is the expected behavior incase of a bug:- Is to provide hamburger functionality

What is the motivation / use case for changing the behavior?
Open Source

I want to work on this issue! under GSSOC

**Comment by Sooraj002** [comment]
i would like to fix this issue

**Comment by raghvendra-official** [comment]
I want to work on this issue, Please assign this issue to me under GSSoC'24.

**Comment by mohit-bhandari45** [comment]
guys I already wrote their, I want to work on this issue. Seriously?
