### ISSUE TITLE
DOC: Update documentation for new themes

### ISSUE THREAD

**Issue by EternoSeeker** [EternoSeeker/gameoflife#122]
### What's wrong with the existing documentation

It's not up to date with the new themes that have been added
Issue regarding updation of presets is #70
This issue can be worked under gssoc 24

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Maheshwari-Love** [comment]
@EternoSeeker can you assign this task to me, it will be very helpful for me. I have started working on this .

**Comment by EternoSeeker** [comment]
@Maheshwari-Love you can work on it
