### ISSUE TITLE
[UI Enhancement] - Improve the website in mobile version and make it more appealing.

### ISSUE THREAD

**Issue by NilanchalaPanda** [EternoSeeker/gameoflife#13]
## Description 
I'm submitting this issue to address the look and feel of the website in mobile version which is not very much optimized and user friendly.

- [ ] Bug report
- [ ] Feature request
- [ ] Documentation changes
- [x] Other (UI Enhancement)

## Screenshots
![image](https://github.com/EternoSeeker/gameoflife/assets/110488337/d06c6902-86d1-4954-b0e9-f2cda99af081)

## Steps to reproduce
- [ ] View the website in mobile.

I would love to work on the issue and contribute to **gameoflife** as a GSSoC'24 Contributor. Looking forward for your reply.

**Comment by raghvendra-official** [comment]
I want to work on this issue, Please assign this issue to me under GSSoC'24.

**Comment by mohit-bhandari45** [comment]
I also want to work on this issue, Please assign me under GSSoC'24.

**Comment by EternoSeeker** [comment]
#12 This issue is already being work on, since I am not sure what exact changes you are going to propose, please wait. it may be possible we require some more enhancements later. I'll let you know @NilanchalaPanda, thank you

**Comment by NilanchalaPanda** [comment]
Hey @EternoSeeker, is the issue still valid and if yes can you please assign it to me. Looking forward for your response.

**Comment by EternoSeeker** [comment]
> Hey @EternoSeeker, is the issue still valid and if yes can you please assign it to me. Looking forward for your response.

If you have more ideas for mobile version please tell

**Comment by NilanchalaPanda** [comment]
Will update upon that by today evening.
