### ISSUE TITLE
BUG: Text selection has to turned off.. text is getting selected

### ISSUE THREAD

**Issue by SuhainaFathimaM** [EternoSeeker/gameoflife#131]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Text selection has to turned off.. text is getting selected

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
sure you can work on it
