### ISSUE TITLE
Feat:Dark Mode Feature

### ISSUE THREAD

**Issue by Shivam250702** [EternoSeeker/gameoflife#132]
### Describe the feature

I want ot add a dark mode feature to reduce the eye fatigue to different kinds of users

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/103785990/da722818-f2c0-4e0d-bd31-defe8a5cec42)

I want to make the right section looks black to reduce eye fatigue

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Black and white theme already exists, do you have any other theme or idea for dark mode, please tell

**Comment by EternoSeeker** [comment]
@Shivam250702 you can add 2 more themes, no problem
Sky blue seems good, and one more unique theme please

**Comment by EternoSeeker** [comment]
okay
