### ISSUE TITLE
Feat:Imporving UI of How to Play page. 

### ISSUE THREAD

**Issue by PuR-vI** [EternoSeeker/gameoflife#133]
### Describe the feature

I want to improve and add dynamic effects and make the how to play page more attractive and engaging please assign it to me under GSSOC'24. And i will add a backgroound iimage to it .

### Add ScreenShots

Something like this. 
![image](https://github.com/EternoSeeker/gameoflife/assets/97090750/3f27fcaf-3ea7-40f6-84d9-b6fbea67e94b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Do you mean to modify the game rules page ? @PuR-vI
Can you give more details, thank you

**Comment by PuR-vI** [comment]
No not change the rules i just mean make it look better and engaging and match the theme

**Comment by harshcodesit** [comment]
hey @EternoSeeker ,

idea:- By incorporating div CSS and animations, I can design the UI in an interactive manner, making it visually appealing.
make the footer immersive

Please assign this task to me,

**Comment by EternoSeeker** [comment]
@PuR-vI I'm giving it level2 since I had requested more changes

**Comment by PuR-vI** [comment]
Thankyou
