### ISSUE TITLE
BUG:Switch to Gradient Theme is not working

### ISSUE THREAD

**Issue by karthickkumarsm** [EternoSeeker/gameoflife#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Switch to gradient theme is not working and it is not showing any options when the option is clicked

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
you can start working on it
