### ISSUE TITLE
Feat: Implement Dedicated "About" Page

### ISSUE THREAD

**Issue by Amruta7203** [EternoSeeker/gameoflife#135]
### Describe the feature

Currently, clicking the "About" link redirects users to the website's GitHub repository. This provides technical information, but it's not ideal for users seeking a high-level overview of the website and its team/purpose.

Proposed Solution:

Create a dedicated "About Us" page within the website itself. This page should  explain:

The website's purpose and goals.
The game rules.
Settings, themes, etc.

Benefits:

Improved user experience: Users can easily access information about the website without leaving the site and navigating to an external platform.
Clearer communication: A dedicated page allows for a well-structured and informative presentation of "About Us" content, leading to a better understanding of the website.
Branding and storytelling: The "About Us" page can be used to establish the website's brand identity and connect with users on a more personal level.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/116087736/370c57bb-464e-465b-a0a9-f6dd8469a7ba)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
there is a game rules page, if you want to make further modifications to it, you can go ahead @Amruta7203

**Comment by Amruta7203** [comment]
Hi @EternoSeeker I was thinking about adding an about page to the website which will contain the same information as in the github repo with some modifications. so that the user won't be redirected to github, instead the user can continue in the website itself.

**Comment by EternoSeeker** [comment]
Actually @Amruta7203 , the current game rules page has similar information as documentation
If you plan to add some new information or some guide maybe, you can go ahead with it
