### ISSUE TITLE
BUG: Non-uniform hover effect throughout the website

### ISSUE THREAD

**Issue by Amruta7203** [EternoSeeker/gameoflife#136]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Currently, the hover effects are not applied consistently across the website. This inconsistency can be confusing for users and detract from the overall user experience.
Some elements(like buttons, links) have hover effect while some do not. This makes the website feel unprofessional and unpolished.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Sure, you can start working on it

**Comment by harshcodesit** [comment]
hey @EternoSeeker,
My name is Harshwardhan Singh Panwar and I'm a contributor at GSSOC'24 .

idea:- By incorporating div CSS and animations, I can design the hover effect in an interactive manner, making it visually appealing.

Please assign this task to me, GSSOC'24 .
