### ISSUE TITLE
BUG:Navbar is not Responsive and nav links not aligned properly.

### ISSUE THREAD

**Issue by mohangolakoti** [EternoSeeker/gameoflife#138]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hello @EternoSeeker,

-Navbar is not responsive for mobile and tablet devices.
-The nav links are not properly aligned on mobile and tablet devices.

Please assign me this issue, and I will make the navbar responsive for all devices.

Screenshot:
![convay-nav-issue](https://github.com/EternoSeeker/gameoflife/assets/116739999/3a483231-9dcc-474f-8030-e2e8a26d86f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Yes @mohangolakoti you can start working on it
