### ISSUE TITLE
BUG: Responsiveness of the Home Page

### ISSUE THREAD

**Issue by AMS003010** [EternoSeeker/gameoflife#150]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The responsiveness of the Home Page and the side panel fails under screen resolutions of 768px. This issue can be fixed with  appropriate html, css being applied.
<br/>
Screenshots
![image](https://github.com/EternoSeeker/gameoflife/assets/111883236/a3d3bec4-d80f-45d2-b241-b396fd4c6dac)
![image](https://github.com/EternoSeeker/gameoflife/assets/111883236/fba0bd5c-5bc1-4a5d-8fae-81b9b938a8d5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
@AMS003010 sure you can work on it

**Comment by AMS003010** [comment]
@EternoSeeker I have made the PR with the required changes, please do review it

**Comment by EternoSeeker** [comment]
> @EternoSeeker I have made the PR with the required changes, please do review it

yes, thank you
