### ISSUE TITLE
Enhancement: Containerization and Style Refinement for Game Rules Page

### ISSUE THREAD

**Issue by adityas-github** [EternoSeeker/gameoflife#153]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I can enhance the Game Rules page by containerizing elements for better organization and refinement styles to improve visual appeal.

**Changes That Can Be Made**:
1. **Containerization**:
   - Organize elements within a container to improve structure and readability, ensuring a coherent presentation of content.
   - Implement proper alignment and spacing within the container to create a visually appealing layout that enhances user experience.

2. **Style Refinement**:
   - Update styles such as font colors, sizes, and alignments to better match the desired theme and improve overall aesthetics.
   - Adjust background colors and contrast to ensure readability and visual consistency across the page.

**Expected Behavior**:
- After implementing the changes, the Game Rules page should demonstrate improved organization and visual appeal through containerization and style refinement.

![Screenshot 2024-05-29 at 11 39 04 PM](https://github.com/EternoSeeker/gameoflife/assets/98210910/9a34b847-80dd-42a9-9cbf-6e2037442e44)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
sure @adityas-github you can work on it
