### ISSUE TITLE
BUG: Favicon is not displayed properly on the Game Rules page.

### ISSUE THREAD

**Issue by sweta-singh28** [EternoSeeker/gameoflife#157]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The favicon on the game rules page should be displayed the same as that on the home page instead, no favicon is being displayed. Please assign me this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
okay you can work on it
