### ISSUE TITLE
Adding 'How it works' section to let users know.

### ISSUE THREAD

**Issue by AtharvKasar04** [EternoSeeker/gameoflife#16]
## I'm submitting a ...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

- I would like to add a 'How-it-works' button or a tab where the explanation of Conway's game of life is present and how it works.
- As users will then be able to know exactly what the project is and how it works.

@EternoSeeker Can you please assign this issue to me under GSSoC'24, I would love to work on this addition.
I have previously submitted couple of PR's under GSSoC'24 in different repo's.

Thank You!

**Comment by BagchiShreya** [comment]
Hi @EternoSeeker I would like to work on this feature and enhance this already amazing project of yours. This feature would help the 1st time users/players of this game to understand the working of the Conway's way of life. It would be great if you assign this issue to me. This contribution would be for GSSoC'24.

**Comment by EternoSeeker** [comment]
@AtharvKasar04 you can start working on it, although I recommend waiting a bit. There are some changes that others may make and we can have merge conflicts, you may have to wait till some previous issues get resolved, thank you for your patience

**Comment by AtharvKasar04** [comment]
> @AtharvKasar04 you can start working on it, although I recommend waiting a bit. There are some changes that others may make and we can have merge conflicts, you may have to wait till some previous issues get resolved, thank you for your patience

Sure @EternoSeeker  I'll wait till those issues are successfully merged and then I'll open my PR. 
Thank you for assigning :)

**Comment by EternoSeeker** [comment]
@AtharvKasar04 any updates ?

**Comment by AtharvKasar04** [comment]
> @AtharvKasar04 any updates ?

Hey @EternoSeeker Can i submit the PR in just 1-3 days as currently my End-sem exams are going on! Apologies for the delay caused :/

**Comment by EternoSeeker** [comment]
Alright @AtharvKasar04 no worries
