### ISSUE TITLE
Feat: Improving the Navbar

### ISSUE THREAD

**Issue by woodwolfswee** [EternoSeeker/gameoflife#165]
### Describe the feature

The transitions and the few of the animations are rough around the edges. I could help improve it and smoothen out the animations. Please assign this task to me so that I can work on it.

### Add ScreenShots

![Screenshot_30-5-2024_223443_eternalgameoflife netlify app](https://github.com/EternoSeeker/gameoflife/assets/90133892/9b9bbbce-ed61-4baf-b2ba-50c11585152c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vverma022** [comment]
Can I work on this simultaneously as well ?
