### ISSUE TITLE
Feat: Multiple box selection when mouse is pressed down and dragged across grid

### ISSUE THREAD

**Issue by MadhurimaNayak** [EternoSeeker/gameoflife#167]
### Describe the feature

I would like to add a feature that lets the user select multiple boxes at one time while dragging the mouse across the grid. The user would need to press down the mouse and drag in order to do so. 
_Why is this important?_
Right now, it allows the user to just select one box at a time, which is tedious for the user + to run a successful animation you need to have multiple boxes selected, which is time taking with the current feature. 

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/124715194/e4981837-1d24-491b-b708-a76ea842f745)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by MadhurimaNayak** [comment]
hey @EternoSeeker, please assign this issue to me.

**Comment by EternoSeeker** [comment]
Sure @MadhurimaNayak , you can work on it

**Comment by MadhurimaNayak** [comment]
alright, will keep you updated!

**Comment by EternoSeeker** [comment]
yes
