### ISSUE TITLE
Feat: Enable clear while playing

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#169]
### Describe the feature

Currently to clear the screen, we first have to pause the game. Pressing clear while the game is in play, doesn't do anything.

### Add ScreenShots

In this case
![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/a4c536f8-1ba4-4470-9d8d-d36c5e82863e)
Even when I am pressing the clear button, it doesn't clear.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
it's the intended behaviour
