### ISSUE TITLE
Making the whole website Responsive-

### ISSUE THREAD

**Issue by Pujan-sarkar** [EternoSeeker/gameoflife#17]
## I'm submitting a ...

- [X] Bug report
- [X] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

## Current behaviour
In the current situation the website is not fully responsive for that it maybe create a problem for the user who will use the website from other devices.

## What is the motivation / use case for changing the behavior?
I will try to make the whole interface Responsive under GSSOC'24. I will try to make settings part also responsive by changing some required changes in UI. @EternoSeeker will you please assign this problem to me

**Comment by EternoSeeker** [comment]
This ui changes may conflict with other people who are also working, I suggest you to wait for a while before working on the issue. Don't worry it'll be assigned to you, thanks for your patience.

**Comment by Pujan-sarkar** [comment]
@EternoSeeker this issue is kind a solved but some improvement we can do now , so now what will i do should close this issue or what ?

**Comment by EternoSeeker** [comment]
> @EternoSeeker this issue is kind a solved but some improvement we can do now , so now what will i do should close this issue or what ?

If you have any further ideas, then do suggest

**Comment by Pujan-sarkar** [comment]
@EternoSeeker okay i am waiting someday after other make some changes then i will try to make it responsive ....
