### ISSUE TITLE
Feat: User can change Opacity of grid and bricks as well

### ISSUE THREAD

**Issue by Yashgabani845** [EternoSeeker/gameoflife#170]
### Describe the feature

i want to add this feature in this project
i want to add one slider which will allow user to change opacity of grid and 
one more slider to change opacirty of bricks 
it would be good feature

### Add ScreenShots

User can remove thsi grids is possible currrently after this feature user will able to change opaciy
![Screenshot (213)](https://github.com/EternoSeeker/gameoflife/assets/127788321/519c6cf8-c91c-407b-b569-b8d50283f9e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Yashgabani845** [comment]
@EternoSeeker  please assign me this issue

**Comment by EternoSeeker** [comment]
you can add that in the settings below the random slider
