### ISSUE TITLE
BUG: enhancing the text colour in cyberpunk theme

### ISSUE THREAD

**Issue by karthickkumarsm** [EternoSeeker/gameoflife#171]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/EternoSeeker/gameoflife/assets/89688112/3a37e466-b3d7-43b1-beec-da72c537ce40)
I like to contribute under GSSoC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
you can work on it

**Comment by rohir1132yadav** [comment]
i want to work on this project .please assign me

**Comment by EternoSeeker** [comment]
@karthickkumarsm any updates ?

**Comment by karthickkumarsm** [comment]
> @karthickkumarsm any updates ?

Bro I am working on it will make a PR tomorrow.I just stuck with some unexpected work.

**Comment by Sayantan-Karmakar** [comment]
I want to Work on this issue. Kindly please assign this task to me
### **How to approach**
Using CSS  command text-color
### **Code of Conduct**
I follow **CONTRIBUTING GUILDLINES**

**Comment by karthickkumarsm** [comment]
PR has been created. Kindly verify it
