### ISSUE TITLE
BUG:doesn't work theme button

### ISSUE THREAD

**Issue by shuhaki** [EternoSeeker/gameoflife#173]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

<img width="1437" alt="Screenshot 2024-06-01 at 1 27 32 AM" src="https://github.com/EternoSeeker/gameoflife/assets/145912232/ee46d0ad-e716-4353-846a-ce3a85a7fdf8">
after click doesn't change theme

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
@shuhaki can you explain it in more detail
