### ISSUE TITLE
BUG: The Home icon looks out of place

### ISSUE THREAD

**Issue by Amruta7203** [EternoSeeker/gameoflife#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The home icon in the game rules page is not compatible with the theme of the website. It decreases the intensity of user interface.

![image](https://github.com/EternoSeeker/gameoflife/assets/116087736/9f2b862c-9680-4962-b03c-5850a19f2361)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
@Amruta7203 you can also make it more responsive, and better looking for small screens
