### ISSUE TITLE
Feat: Adding a custom scroll bar 

### ISSUE THREAD

**Issue by Amruta7203** [EternoSeeker/gameoflife#176]
### Describe the feature

The side navbar requires a custom scroll bar aligned to the theme of the website for better user experience.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/116087736/c6c23f0b-89bb-4e57-8b6c-5ca0e26136e6)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Yes, the scroll bar color is not visible on initial loading. You can work on it
