### ISSUE TITLE
Feat: Addition of Custom Cursor , preloader and Scroll bar.

### ISSUE THREAD

**Issue by Anjaliavv51** [EternoSeeker/gameoflife#177]
### Describe the feature

Custom Cursor.
Preloader.
Scroll Bar.

### Add ScreenShots

![Screenshot 2024-06-01 172517](https://github.com/EternoSeeker/gameoflife/assets/154777864/ac47b303-1be7-460d-9e58-f6f264caf2a7)

![Screenshot 2024-06-01 133828](https://github.com/EternoSeeker/gameoflife/assets/154777864/a6ef8f78-60a6-43d3-b66c-b9c2b3d58b68)

![image](https://github.com/EternoSeeker/gameoflife/assets/154777864/fea89906-a51c-4e14-81c2-62008987bf61)

![image](https://github.com/EternoSeeker/gameoflife/assets/154777864/df381532-3267-4902-a18f-19a0ca3e637a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Scroll bar is already being worked on, you can work on the other 2.

**Comment by Anjaliavv51** [comment]
@EternoSeeker please review the PR.
