### ISSUE TITLE
BUG: Position of home button

### ISSUE THREAD

**Issue by GitNinja-bcd** [EternoSeeker/gameoflife#180]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Home button is not positioned correctly on the game rules page, which is not aesthetically pleasing.
![Screenshot (10)](https://github.com/EternoSeeker/gameoflife/assets/158538244/6fdbba8d-2e4a-42df-a3a6-1879625a8d70)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
It's being worked on already

**Comment by EternoSeeker** [comment]
#175

**Comment by GitNinja-bcd** [comment]
Okay
