### ISSUE TITLE
Feat: Add icons on Presets options

### ISSUE THREAD

**Issue by GitNinja-bcd** [EternoSeeker/gameoflife#181]
### Describe the feature

Icons can be added to the options under Presets, such as Quadpole, Spider, Pulsar, Circle of Fire, etc.
This will further enhance it.

### Add ScreenShots

![most2](https://github.com/EternoSeeker/gameoflife/assets/158538244/6f90a047-56bc-404b-98dd-eb8e107e83f8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
nice idea you can work on it

**Comment by GitNinja-bcd** [comment]
Thank you.

**Comment by EternoSeeker** [comment]
@GitNinja-bcd It's a good practice to mention the respective issue in the PR, Thank you

**Comment by GitNinja-bcd** [comment]
You're welcome
