### ISSUE TITLE
Feat: Dark Mode

### ISSUE THREAD

**Issue by mohit-bhandari45** [EternoSeeker/gameoflife#186]
### Describe the feature

So currently the webpage doesn't have any dark mode feature.
I can implement that.

Just add a level 3 label to it, as I am a gssoc24 contributor.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/151373021/274bcbf7-56e3-4941-8b63-6e7de93d124f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by solanki505** [comment]
I would like to work on this issue

**Comment by EternoSeeker** [comment]
It has black and white theme already
