### ISSUE TITLE
BUG:Add hover color and hover text

### ISSUE THREAD

**Issue by AkhilaSunesh** [EternoSeeker/gameoflife#188]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/EternoSeeker/gameoflife/assets/140897461/dcb8f049-f7cc-4085-830a-8919c4881e54)
Add **hover color  and hover text** to improve readability for the home button.

Kindly assign this issue to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
home button looks different after the recent pr, please check, you can work on it
