### ISSUE TITLE
[UI] Add Gradient Theme Button 

### ISSUE THREAD

**Issue by aditya-bhaumik** [EternoSeeker/gameoflife#19]
## I'm submitting a ...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

## Current behaviour
Users can only select from a set of predefined color themes 

## What is the motivation / use case for changing the behavior?

I would like to add a new feature to allow users to switch to gradient theme and decide on which color they can use in the gradient theme. Also the user can decide on which type of gradient they want in the background. This can help in enhancing the user experience
 
Could you please assign me this issue under GSSoC'24

**Comment by soham-hecker** [comment]
@EternoSeeker  I am interested in contributing to adding the gradient theme feature to the game, by which players can chose the gradient theme of their choice. Please assign this task to me under GSSOC'24.

**Comment by aditya-bhaumik** [comment]
@EternoSeeker Resolved this issue at PR #37
