### ISSUE TITLE
Feat: Add Back To Top button in Game Rules section

### ISSUE THREAD

**Issue by Damini2004** [EternoSeeker/gameoflife#191]
### Describe the feature

This is will help user to to avoid scrolling in order to reach the top section of the Game

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/119414762/74352654-eea3-4db2-87af-1bb910edc06f)

Here as per this button will implement.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
sure you can work on it @Damini2004 , also make it consistent for small devices
