### ISSUE TITLE
BUG: Initial Grids Overflow and Styling Errors

### ISSUE THREAD

**Issue by shreyash3087** [EternoSeeker/gameoflife#193]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

**Description:**

The Grids Overflow its Container untill its grid size is changed,also the styling for the change grid size button is not proper

**Steps to Reproduce:**

- Go to [gameoflife](https://eternalgameoflife.netlify.app/)
- Notice the Overflow of Grids
- Decrease the screen width
- Notice the improper styling of the buttons that overflow the screen.

**Screenshots:**

![screencapture-eternalgameoflife-netlify-app-2024-06-04-19_18_50](https://github.com/EternoSeeker/gameoflife/assets/72603662/f5f9294b-1065-4c0b-90f0-a4a5020e2eca)

**Additional Context:**
N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by shreyash3087** [comment]
@EternoSeeker can i work on this?, also there should be a limit for the grid size otherwise if a user enters a very large number lets say 1000 or 10000 in the grid size it would crash the webpage,i can fix all these errors

**Comment by EternoSeeker** [comment]
@TiwariRahul16 were already working on it, in their followup PR

**Comment by shreyash3087** [comment]
@EternoSeeker Alright =) Is there anything left for me then? I'll check,no worries

**Comment by shreyash3087** [comment]
Closing this issue

**Comment by EternoSeeker** [comment]
> @EternoSeeker Alright =) Is there anything left for me then? I'll check,no worries

I do want to expand the scope of the project, then everyone will have lot of stuff to do, let's see.
