### ISSUE TITLE
Feat: Improper gap/alignment of controls

### ISSUE THREAD

**Issue by NeerajaGurram** [EternoSeeker/gameoflife#195]
### Describe the feature

the gird and controls are overlapping and it doesn't look good.
so i would like to work on this by adjusting the gap between them.
please assign me this under gssoc and give appropriate labels to it.
thankyou.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/152693538/ec590ad4-83d0-4c6f-a82b-cb3b50b2754b)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
It's already being worked on
