### ISSUE TITLE
BUG: Black & White theme Update

### ISSUE THREAD

**Issue by Yashaswale** [EternoSeeker/gameoflife#198]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

bug: when we deselect the gridlines option and change the theme to black and white the screen goes white 
![1](https://github.com/EternoSeeker/gameoflife/assets/117583791/564a3442-0a81-49ae-98c6-bb0d8b7a9a34)
I like to contribute under GSSoC'24

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by partha120804** [comment]
Self
I want to work on this issue.

**Comment by partha120804** [comment]
self

**Comment by partha120804** [comment]
@EternoSeeker My PR also closed this Issue but it wasn't labeled, will it count towards my contribution or not ?
