### ISSUE TITLE
Feat: Custom theme creator with color picker

### ISSUE THREAD

**Issue by partha120804** [EternoSeeker/gameoflife#199]
### Describe the feature

You can pick your 
- Foreground
- Background
- Text Color

This will make the site more beautiful and customizable

### Add ScreenShots

<img width="248" alt="image" src="https://github.com/EternoSeeker/gameoflife/assets/138643473/535c3484-63e9-4f41-b7d8-ac83b099a0f8">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by partha120804** [comment]
@EternoSeeker Please Assign me to work on this issue

**Comment by partha120804** [comment]
Self

**Comment by partha120804** [comment]
Although the bot assigned the project to me how to label the project under GSSOC and task level ?

@EternoSeeker

**Comment by EternoSeeker** [comment]
> Although the bot assigned the project to me how to label the project under GSSOC and task level ?
> 
> @EternoSeeker

it's labeled by me, you can work on the issue now

**Comment by partha120804** [comment]
Hello PA ( @EternoSeeker  )

I have created a PR, please verify it.
