### ISSUE TITLE
Feat: Display Number of Live Births and Deaths

### ISSUE THREAD

**Issue by An0nym0us092** [EternoSeeker/gameoflife#200]
As a contributor to GSSoC '24, I propose adding a feature to our implementation of Conway's Game of Life that displays the number of live births and deaths occurring in each generation. This feature will enhance the user experience by providing insightful metrics about the evolution of the game board over time.

Benefits:
Provides users with additional insights into the dynamics of the game.
Enhances the educational value by highlighting the patterns and rules governing cell changes.
Supports analysis and debugging of the game's behavior.

Implementation Plan:
Tracking Births and Deaths:
Modify the game logic to count the number of cells that transition from dead to alive (births) and from alive to dead (deaths) in each generation.

User Interface:
Design a UI component that displays the number of live births and deaths after each generation update.
Ensure the UI is intuitive and integrates seamlessly with the existing game interface.

Data Presentation:
Present the birth and death counts in a clear and accessible manner, possibly through a side panel or overlay on the game board.

Technical Details:
Game Logic: Modify the existing logic to include counters for births and deaths.
Frontend: Design and implement UI elements for displaying the statistics.
Data Handling: Ensure efficient data storage and retrieval for performance optimization.

### Add ScreenShots

![idea](https://github.com/EternoSeeker/gameoflife/assets/156635184/4cca555b-93a1-45bb-ac70-5f34f20dc812)

Can you please assign this issue to me.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by An0nym0us092** [comment]
self

**Comment by An0nym0us092** [comment]
@EternoSeeker Can you please assign labels to this issue, I want to work on it under gssoc'24.

**Comment by EternoSeeker** [comment]
You can work on it

**Comment by An0nym0us92** [comment]
self

**Comment by partha120804** [comment]
self
