### ISSUE TITLE
Feat: Correct labelling if button

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#201]
### Describe the feature

Currently the time controlling buttons are called "Rewind" and "FastForward", instead they should be called "Slow Down" and "Speed Up" respectively

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/35a9a3b8-76b1-4d07-8a0d-7e30f265cca9)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Sure, you can work on it
