### ISSUE TITLE
Feat: Add Rule And Instructions :

### ISSUE THREAD

**Issue by KomalSrivastava** [EternoSeeker/gameoflife#202]
### Describe the feature

1. This feature provides users with clear, concise instructions on how to play the Game of Life, explaining the game's rules, controls, and functionalities.
2. Provides a better understanding of the game to new users.
3. Enhances the user experience by reducing confusion and making the game more accessible.

### Add ScreenShots

Here we can add a section of Rule And Instructions so it will be convenient for the user to understand the game.
![image](https://github.com/EternoSeeker/gameoflife/assets/132221203/1ab8bc62-389a-4a5b-9969-8b6f728bd1b2)

@EternoSeeker Please assign me this issue i will work on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
game rules page already exists
