### ISSUE TITLE
Feat: Adding a logo

### ISSUE THREAD

**Issue by KomalSrivastava** [EternoSeeker/gameoflife#203]
### Describe the feature

@EternoSeeker We can add a logo to the website. I have experience with designing. Please design it to me under Gssoc.

### Add ScreenShots

![Screenshot 2024-06-06 023450](https://github.com/EternoSeeker/gameoflife/assets/132221203/89fc575f-1f94-4e7e-b779-d5b1b0bb4c92)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Sure, you can work on it

**Comment by KomalSrivastava** [comment]
@EternoSeeker Thank you sir for assigning me this issue , I'll give you update after few days.

**Comment by KomalSrivastava** [comment]
I have created a logo..

![image](https://github.com/EternoSeeker/gameoflife/assets/132221203/d4ef3ace-247e-4c94-8241-0e2b291b3a11)
