### ISSUE TITLE
Feat: Change or Improve Buttons :

### ISSUE THREAD

**Issue by KomalSrivastava** [EternoSeeker/gameoflife#204]
### Describe the feature

I can change button as given below , this is not looking good i can improve it. 
@EternoSeeker Please assign me this issue , i will work on it.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/132221203/e9b9ea89-94d1-4e66-be93-38e8aadc8fd2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
@KomalSrivastava above screenshot is not of my project

**Comment by KomalSrivastava** [comment]
@EternoSeeker I have pasted this screenshot by mistake my apology. I was talking about these buttons which you can see below:-
![Screenshot 2024-06-06 195457](https://github.com/EternoSeeker/gameoflife/assets/132221203/7678498e-7fa6-43b3-99af-8fc650419875)
Please assign me this issue.. i can modify it which will make it look better then previous.

**Comment by EternoSeeker** [comment]
okay, you can work on it

**Comment by KomalSrivastava** [comment]
@EternoSeeker Hello Sir , Kindly merge this after this i will make pull request of my next issue which is  Logo.
