### ISSUE TITLE
Feat: update complete UI 

### ISSUE THREAD

**Issue by dnyandeepchute** [EternoSeeker/gameoflife#207]
### Describe the feature

update complete UI and make it mare attractive

### Add ScreenShots

![Screenshot 2024-06-06 213823](https://github.com/EternoSeeker/gameoflife/assets/158272735/7366335a-ce13-4766-83c9-b3b1b41e1610)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by dnyandeepchute** [comment]
please assign this to me, thank you.

**Comment by EternoSeeker** [comment]
okay, you can fix the initial rendering bug of the grid too

**Comment by EternoSeeker** [comment]
also make sure it stays consistent across devices and easy to work around
