### ISSUE TITLE
Would like to add a page for Game rules

### ISSUE THREAD

**Issue by syannam-12** [EternoSeeker/gameoflife#21]
## I'm submitting a ...

- [ ] Bug report
- [ ] Feature request
- [x] Documentation changes
- [ ] Other (please mention)

**Comment by GayathriPCh** [comment]
@EternoSeeker  I volunteer to take the responsibility to make an awesome page for the Game rules. Could you assign this issue to me? Also could you specify the level for the issue , under GSSOC'24 ?

**Comment by AmrutaZagade** [comment]
Hello @EternoSeeker I would like to add a page for Game rules. Can you please assign me this task

**Comment by EternoSeeker** [comment]
It would be nice to see which one is good, but I'm currently assigning it to @syannam-12

**Comment by EternoSeeker** [comment]
@syannam-12 any updates ?

**Comment by syannam-12** [comment]
I'm halfway through. I'll finish it within 2 days.

**Comment by syannam-12** [comment]
@EternoSeeker <https://github.com/EternoSeeker> I have added the page for
game rules and submitted a PR yesterday. I request you to check it out
once..!!
