### ISSUE TITLE
BUG: Weird effect in website when viewed in mobile

### ISSUE THREAD

**Issue by arpy8** [EternoSeeker/gameoflife#213]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Notice the bottom and the right edge

Screenshot for reference:
![image](https://github.com/EternoSeeker/gameoflife/assets/74809468/4a5fc44e-ca07-4ec4-8d4d-7f9e89b955c5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
You can work on it
