### ISSUE TITLE
Feat: Improvement in the Gradient Theme

### ISSUE THREAD

**Issue by partha120804** [EternoSeeker/gameoflife#218]
### Describe the feature

I think this Gradient theme can be improved by adding a more informed way to choose colors and a gradient slope slider, instead of the 4 default drop down menu.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/138643473/fd7ec6af-594f-4772-8d5e-8c03953e0b5a)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by partha120804** [comment]
Self

**Comment by EternoSeeker** [comment]
you can work on it
