### ISSUE TITLE
Develop a creative and visually appealing home page for starting the game

### ISSUE THREAD

**Issue by syannam-12** [EternoSeeker/gameoflife#22]
## I'm submitting a ...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

**Comment by EternoSeeker** [comment]
You can work on this after you have completed the previous issue, thank you.

**Comment by codebreaker3008** [comment]
@EternoSeeker  can you assign this to me please ?

**Comment by codebreaker3008** [comment]
@EternoSeeker  can you assign this to me ??

**Comment by syannam-12** [comment]
Thank you for assigning this task to me. I will do my best!!

**Comment by syannam-12** [comment]
Thank you for assigning this task to me. I will do my best.!!

**Comment by Yuvraj960** [comment]
@EternoSeeker Please assign this issue to me

**Comment by Ananya-Nair20** [comment]
@EternoSeeker I would like to take up this task under GSSOC'24 as it allows me to use my artistic skills to enhance your project. Could you assign this issue to me?
