### ISSUE TITLE
Adding a contact us page allowing users to give their valuable feedback 

### ISSUE THREAD

**Issue by Khushipawar37** [EternoSeeker/gameoflife#221]
### Describe the feature

I feel that a game becomes best when their is certain sort of connection between the user and admin. If the user faces any issue while gaming or he feels to thank the owner, there must be such a page that allows them to give their feedback.

### Add ScreenShots

I will share the UI design if you are interested in adding this page to your website. 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Khushipawar37** [comment]
Self

**Comment by EternoSeeker** [comment]
#53 it's already worked on in this issue
