### ISSUE TITLE
Feat: Modify Project structure and declutter

### ISSUE THREAD

**Issue by EternoSeeker** [EternoSeeker/gameoflife#227]
### Describe the feature

1. Some files are not being used in the project like package.json
2. CSS files can be under a CSS directory, the js files in root directory can be under js directory and HTML files can be kept as it is
3. Modify the respective paths after rearranging, so ensure smooth working

### Add ScreenShots

![Screenshot 2024-06-08 093954](https://github.com/EternoSeeker/gameoflife/assets/86345498/788639f3-0ba1-4ffc-a88e-5eb08dd8bf18)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by adityas-github** [comment]
I want to work on this issue. Please assign me this issue.I am GSSoC 2024 contributor
