### ISSUE TITLE
BUG: improve the ui for mobile view

### ISSUE THREAD

**Issue by parikhitritgithub** [EternoSeeker/gameoflife#230]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

 clear button is not visible in mobile view, and some part of the height input bar is also not visible.
![image](https://github.com/EternoSeeker/gameoflife/assets/124444610/81f02720-6132-4ca8-91e5-bbbca5794456)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
you can work on it
