### ISSUE TITLE
Feat: No Re-loding of Settings/Side-nav

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#232]
### Describe the feature

The side-nav loads in a fancy way when the site is opened for the first time, but if I close the nav-bar, and open it once again, it reloads in the same way. 
I suggest that it should load like that only when visiting the site for the first time, and be as it is when we open it, after closing the settings.

### Add ScreenShots

Loading of nav-bar:
![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/e5410ec5-df8c-4c93-a7d2-b54f5981ea8b)
If I open it again after pressing this button:
![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/8aefce66-f555-454d-8e89-cd60948f97ae)
It loads in the similar manner.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Sure you can work on it
