### ISSUE TITLE
BUG:Add Validation in Feedback Form

### ISSUE THREAD

**Issue by Vibhu315** [EternoSeeker/gameoflife#238]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The Feedback form has no validation. We can add validation in Feedback Form.

Problem:

https://github.com/EternoSeeker/gameoflife/assets/93249125/9532f370-9ab6-4227-99fe-e0949c278ef0

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vibhu315** [comment]
hey @EternoSeeker , 
I can fix this issue . Please assign me this issue

**Comment by EternoSeeker** [comment]
thank you
