### ISSUE TITLE
Feat:Update the design of game 

### ISSUE THREAD

**Issue by Bhumika1312** [EternoSeeker/gameoflife#244]
### Describe the feature

I am planning to improve the overall game design by introducing a variety of visually appealing themes and presets that will elevate the aesthetic quality of the game

Kindly assign this issue to me under GSSOC'24
Thank you

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/115869626/3e01c193-c584-4a92-98be-5dafc8ad3332)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Please elaborate what changes you would make, thank you

**Comment by Bhumika1312** [comment]
I would like to add themes and some presets also want to make buttons position proper

**Comment by Shubham-Zone** [comment]
@EternoSeeker please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by EternoSeeker** [comment]
> Reference

there are many presets now, you can add 1 preset and 1 theme, also the design of the buttons is being worked on, let's see
