### ISSUE TITLE
Feat: Enhance the speed controlling Buttons

### ISSUE THREAD

**Issue by partha120804** [EternoSeeker/gameoflife#248]
### Add ScreenShots

# Currently it looks like this 
![image](https://github.com/EternoSeeker/gameoflife/assets/138643473/d57670cd-30d6-4208-b6e7-fe9f9f96f17f)

---

# This feature will make it look like this
<img width="221" alt="image" src="https://github.com/EternoSeeker/gameoflife/assets/138643473/576c3f34-3e51-492a-a4e1-8dd06df4ba3f">

---

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by partha120804** [comment]
self

**Comment by EternoSeeker** [comment]
you can work on it
