### ISSUE TITLE
Feat:Add popular presets 

### ISSUE THREAD

**Issue by chinmaylothe** [EternoSeeker/gameoflife#249]
### Describe the feature

These presets will add diversity, complexity, and visual appeal to the game, enriching the user experience for players and enthusiasts alike.

### Add ScreenShots

# Middleweight spaceship
![image](https://github.com/EternoSeeker/gameoflife/assets/111881649/4491e140-b976-46c6-a6eb-d700ba7cfcdb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chinmaylothe** [comment]
self

**Comment by adityas-github** [comment]
please asign this to me
