### ISSUE TITLE
Feat: Adding Error 404 page.

### ISSUE THREAD

**Issue by taneeshaa15** [EternoSeeker/gameoflife#252]
### Describe the feature

A new web page will be added showing error 404.

### Add ScreenShots

![md](https://github.com/EternoSeeker/gameoflife/assets/157527085/43d0e72f-f092-44f1-bc93-9f92cbfbbf7d)
It will somehow look like this (not exactly) and will redirect the user to homepage.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by taneeshaa15** [comment]
@EternoSeeker Please assign me this issue under gssoc'24 level 2.

**Comment by Shubham-Zone** [comment]
@EternoSeeker please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
