### ISSUE TITLE
Feat: Hover effect

### ISSUE THREAD

**Issue by dishathakurata** [EternoSeeker/gameoflife#254]
### Describe the feature

Adding hover effect on settings texts.

### Add ScreenShots

![settings](https://github.com/EternoSeeker/gameoflife/assets/146114938/526b0c26-be1c-4086-99bf-fa17d1c058bc)

Suggest color that you want to hover.

Assign this to me under GSSoC'24.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
@EternoSeeker please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by EternoSeeker** [comment]
you can use a color that is vibrant, and a shade of the theme currently applied
