### ISSUE TITLE
Feat:Redesign Feedback Page

### ISSUE THREAD

**Issue by zalabhavy** [EternoSeeker/gameoflife#257]
### Describe the feature

Feedback page is not looks attractive.
There is no margin from top and bottom.
I will create new feedback page with better design and add better options.
In this form also placeholder is not present.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/126322584/681c1bc4-9f6b-4237-9d47-5c15aaf18f75)
![image](https://github.com/EternoSeeker/gameoflife/assets/126322584/1d8514e5-259a-40b1-812c-d6bcae4b7361)

As we can see it does not have proper margins.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Vibha17** [comment]
Hi I am Vibha Gupta and I would like to fix the issue.

I am working under GSSoC'24. Please assign me this issue.

**Comment by Shubham-Zone** [comment]
@EternoSeeker please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development
