### ISSUE TITLE
Feat: Redesign the whole bottom bar buttons

### ISSUE THREAD

**Issue by partha120804** [EternoSeeker/gameoflife#262]
### Describe the feature

I want to work on the bottom bar to make it more uniform and appealing

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/138643473/55e8f87e-cf24-48f9-9b9b-d1eda121acda)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Shubham-Zone** [comment]
@EternoSeeker please assign this to me i am GSSOC'24 contributor and have 2+ years of experience in development

**Comment by partha120804** [comment]
Self

**Comment by partha120804** [comment]
@EternoSeeker ?
The new guidelines make a limit of 150points of contribution per repository for library files ?
What does that mean ? Will it mark my contributions as spam ? Because I am only working on this repo for a long time ?

**Comment by partha120804** [comment]
@EternoSeeker yes you were correct 

I read the rules again and they made it clear that it will only apply to the repos where you can add any ML file or any API and can take points, but not on projects like this. So I can continue contribution.

**Comment by EternoSeeker** [comment]
no worries
