### ISSUE TITLE
Implementing the design with proper color combinations and proper font

### ISSUE THREAD

**Issue by Anou25** [EternoSeeker/gameoflife#27]
I want to bring forth a better design for the website.

The font and color combination are not visually appealing along with the text alignments. Thus , the UI can be improved.

![Screenshot 2024-05-12 093720](https://github.com/EternoSeeker/gameoflife/assets/136624807/6b77dbeb-9ce5-43e4-84d4-7355bd61962a)

Hence, I would like to make the design more appealing with proper font and color palate combination.
Point down the features
1. Want to make UI design more exiting for a Game user interface
2. Add more colors which will be suitable for the game.

@EternoSeeker  please can you assign this task to me.

**Comment by EternoSeeker** [comment]
Yes, it'll be assigned to you. Since other contributors are also working on same files, I ask you to wait before I merge those changes. I'll let you know when you can do a PR

**Comment by Agrima11** [comment]
can u assign this issue to me...i wud love to work on this

**Comment by Anou25** [comment]
@EternoSeeker when can I start working on this issue, please can you assign it to me.
