### ISSUE TITLE
[Fix] :Resizing the  button that are attached 

### ISSUE THREAD

**Issue by Braj-01** [EternoSeeker/gameoflife#270]
### What's wrong with the existing documentation

I've seen that the buttons are very close to each othe r so I would like to fix that.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Please elaborate

**Comment by Braj-01** [comment]
![Uploading IMG_20240614_124338.jpg…]()
See the mark
