### ISSUE TITLE
Feat: Make it responsive

### ISSUE THREAD

**Issue by amamisha59** [EternoSeeker/gameoflife#273]
### Describe the feature

the page is not responsive .I want to work on this issue

### Add ScreenShots

![Screenshot (163)](https://github.com/EternoSeeker/gameoflife/assets/108077898/f8c5dfa5-7e8c-40a0-a99a-66aae74855b0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Anshika-Gochar** [comment]
please assign this issue  to me ,for screen size width 425px and less it is not responsive i can make it responsive under Gssoc'24

**Comment by EternoSeeker** [comment]
sure you can work on it

**Comment by Maheshwari-Love** [comment]
@EternoSeeker can you please assign me this task... it has been 3 weeks long
