### ISSUE TITLE
Feat: Adding more UI in FEEDBACK SECTION

### ISSUE THREAD

**Issue by DhayanandhS** [EternoSeeker/gameoflife#283]
### Describe the feature

Hi @EternoSeeker, as we can see on the [https://eternalgameoflife.netlify.app/feedback.html](Feedback Page) it looks okey I assure you. But I can make it more appealing and attractive. Like changing the background. 

And I had another IDEA in my mind,
File Upload for Feedback page:
The file upload feature allows users to attach screenshots, documents, or other files when submitting feedback. This can help users provide more detailed and visual feedback, improving the overall quality and clarity of their submissions. For this I can make changes in the form.

### Add ScreenShots

![Screenshot 2024-06-14 234021](https://github.com/EternoSeeker/gameoflife/assets/112493275/6bdc7a1c-4cde-4a35-8a2f-dd5ea7303b36)
Here in the form under the feedback type input I can add the file upload option for users.

Can you please assign this issue to me under GSSoC?

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
File upload option can be separate and optional

**Comment by DhayanandhS** [comment]
> File upload option can be separate and optional

ok I will focus on that!
