### ISSUE TITLE
BUG: Custom theme doesn't change the background color after applying gradient

### ISSUE THREAD

**Issue by partha120804** [EternoSeeker/gameoflife#286]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I have to remove gradient every time we apply a custom theme so that the new solid background color should be visible.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by partha120804** [comment]
self

**Comment by EternoSeeker** [comment]
you can work on it
