### ISSUE TITLE
[UI] : Adding animation to sidebar menus

### ISSUE THREAD

**Issue by SaranshBangar** [EternoSeeker/gameoflife#29]
## I'm submitting a ...

- [ ] Bug report
- [X] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

## Current behaviour

The Themes, Presets and History menu just pops out, it would look better if they glide out with an animation

![image](https://github.com/EternoSeeker/gameoflife/assets/114401238/54d2231a-2cb5-42e6-953d-ff9a8573d63d)

## What is the motivation / use case for changing the behavior?

A smooth animation always looks better than a simple pop out, this would greatly enhance the UI of the website

**Comment by pankaj-2503** [comment]
Assign this issue to me i would add loader animation while changing themes to the card.

**Comment by SaranshBangar** [comment]
I am already working on it @pankaj-2503

**Comment by SaranshBangar** [comment]
Resolved in PR #54

**Comment by SaranshBangar** [comment]
Resolved in PR #60
