### ISSUE TITLE
Feat: Improving UI of feedback form

### ISSUE THREAD

**Issue by techinaina** [EternoSeeker/gameoflife#296]
### Describe the feature

The feedback form is very simple . So we need to enhance the UI of feedback page  I can change the background and the form according to the theme .so that it will look attractive to user also it is not properly aligned the heading of feeback form is not clearly visible. I can also aligned it properly . 

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/143960485/ec7daa21-8815-4ef0-a0e4-c0652e2f1385)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by techinaina** [comment]
@EternoSeeker  Please assign me this issue i would like to contribute in your project.
thank you

**Comment by techinaina** [comment]
@EternoSeeker  please assign me this issue .

**Comment by EternoSeeker** [comment]
Feedback form was being worked on already, thank you
