### ISSUE TITLE
Feat: Add About page

### ISSUE THREAD

**Issue by zalabhavy** [EternoSeeker/gameoflife#298]
### Describe the feature

I want to add About page it is not good when we click on about option it's open about in github.
I want to add about page in website like games rule.

### Add ScreenShots

Theme is same like gamesrule page information will be added from readme.md

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
the game rules page already is same as documentation
