### ISSUE TITLE
Issue [UI]: Improve Sidebar Styling

### ISSUE THREAD

**Issue by Saloni-0465** [EternoSeeker/gameoflife#30]
## I'm submitting a ...

- [ ] Design Enhancement request

Description:
The sidebar on the website needs styling enhancements for better aesthetics and usability.

Proposed Solution:

1. Customize the range slider to improve its appearance and functionality.
2. Right now the content of history, presets and themes just pops out straight away.  I want to implement smoother transitions for content presentation in the sidebar.
3. Add color to fonts within the sidebar to improve readability and visual appeal.

@EternoSeeker Please assign me the issue. Would love to work on it.

**Comment by MariaBeatriceNamatovu** [comment]
Additional Proposed solutions:
1.  Create sidebar collapse ability. In case the user would prefer full screen mode.
2. Allow the sidebar size to be adjusted to the preference of the user.
3. Add full screen capability with clicking of a button, and ability to return to normal mode

I would like to also be assigned to this issue

**Comment by EternoSeeker** [comment]
Please keep checking how the site looks regularly, since there are going to be lots of PRs of other contributors too, who are working on the same files. I'll assign the issue to you soon @Saloni-0465 , also nice observation and changes that you suggested @MariaBeatriceNamatovu
