### ISSUE TITLE
BUG: Preset doesn't work as intended if grid size is changed below 30

### ISSUE THREAD

**Issue by partha120804** [EternoSeeker/gameoflife#302]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/EternoSeeker/gameoflife/assets/138643473/3a6d28ed-11aa-4c09-9a78-df69667d1b6c)

The presets are created to be applied on 30x60 grid or a larger grid
If the user applies presets on a grid of smaller size the presets don't work as intended.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by partha120804** [comment]
@EternoSeeker sorry PA i was unable for past few days and will be unable for a few days due to my college exams, but please label the issues raised by me, I will complete them by next week after my exams are over.

**Comment by partha120804** [comment]
self

**Comment by EternoSeeker** [comment]
it's okay
