### ISSUE TITLE
Feat:Improve the UI OF feedback form

### ISSUE THREAD

**Issue by CoderGirl2844** [EternoSeeker/gameoflife#304]
### Describe the feature

The feedback form does not match to the theme of the website so I would like to enhance it

### Add ScreenShots

![Screenshot 2024-06-21 035722](https://github.com/EternoSeeker/gameoflife/assets/155231566/71de623d-390f-4c5c-a87c-a3bfbd4f5ff4)
Please assign this issue to me

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
similar issue has been raised before
