### ISSUE TITLE
BUG: The sidebar and buttons isn't responsive

### ISSUE THREAD

**Issue by r7projects-shayan** [EternoSeeker/gameoflife#308]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is no option visible to close the sidebar in iphones. The close option is only visible for other smartphones bigger than iphones, and other devices or larger screen size.

The layout of the buttons and the gaps between them on smaller devices is not perfect, and some buttons are too close kind of overlapping with one another.

Screenshots

![Screenshot 2024-06-21 221723](https://github.com/EternoSeeker/gameoflife/assets/167475552/64d23633-e773-41b4-9735-ba8f8b7fe86a)
![Screenshot 2024-06-21 221812](https://github.com/EternoSeeker/gameoflife/assets/167475552/90032245-ce1b-4587-9dc8-a4fc51e8fd17)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by r7projects-shayan** [comment]
@EternoSeeker kindly assign me this issue so that I can start working on it

**Comment by EternoSeeker** [comment]
you can work on it

**Comment by r7projects-shayan** [comment]
Alright @EternoSeeker

**Comment by partha120804** [comment]
The play/pause/fast/slow buttons looks to be set to fixed withs you can use variable width (like in the buttons) to resolve it :) 👍🏻
