### ISSUE TITLE
Feat: Adding "ABOUT" section (currently it is redirecting to readme file)

### ISSUE THREAD

**Issue by HarshitGupta1511** [EternoSeeker/gameoflife#310]
### Describe the feature

I want to add "ABOUT" page separately ,that will be redirected when clicked on about, now when we click on about , it is taking us to readme.md file in GitHub repo of project. I want to add separate about page with designing as the homepage.

please assign me this issue @et

### Add ScreenShots

<img width="527" alt="Screenshot 2024-06-22 at 8 53 58 PM" src="https://github.com/EternoSeeker/gameoflife/assets/120268295/358f552b-d41e-41bb-9796-9ecf0f7555e2">
<img width="1200" alt="Screenshot 2024-06-22 at 8 54 13 PM" src="https://github.com/EternoSeeker/gameoflife/assets/120268295/ecbf04f3-91dd-4b21-848c-7e4be93972e1">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
The game rules page covers the same thing as in the documentation. there doesn't seem to be a need of adding an about page
