### ISSUE TITLE
BUG: Settings Icon Not Visible in Dark Neon Theme

### ISSUE THREAD

**Issue by Rupalpy** [EternoSeeker/gameoflife#314]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![Screenshot_20240622_232948](https://github.com/EternoSeeker/gameoflife/assets/121295967/2237f0fa-4023-477e-a680-693598192811)
![Screenshot_20240622_233002](https://github.com/EternoSeeker/gameoflife/assets/121295967/5b456cec-b59f-40b3-8a76-424d01c1df0e)
when i close the settings part in dark neon theme , the icon for settings after it is not visible.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rupalpy** [comment]
@EternoSeeker kindly assign me this issue

**Comment by partha120804** [comment]
Please assign me with this project, i have previously worked on svg files and theme.

**Comment by EternoSeeker** [comment]
they raised it, so I'll assign them for now

**Comment by Rupalpy** [comment]
@EternoSeeker i have solved it and created the pr no #320 . Kindly review and merge it.
