### ISSUE TITLE
Feat: Handling for mobile devies

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#315]
### Describe the feature

The website looks good on a PC, but not on mobile devices in portrait mode.
When the website is firstly loaded, the settings sidebar is open by default, but in many devices the 'X' button to collapse the settings is "hidden". Hidden in the sense that the user would have to scroll left to get the X button in the mobile view. 
In other words, the width of the settings menu is more than that of the mobile devices

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/5952ab53-961c-4e34-b816-f34355f2c3eb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
there is a similar issue raised. let's see what they do

**Comment by VijaySamant4368** [comment]
I am so sorry for not looking at open issues before raising my own.
