### ISSUE TITLE
Feat: Addition of SweetAlert2.0

### ISSUE THREAD

**Issue by partha120804** [EternoSeeker/gameoflife#316]
### Describe the feature

Sweet Alert is JS library which offers a more useful, beautiful and customizable alternative for the default alert boxes.

I works on react but it can be added to any html file without react but with limited features, but those features will be enough for this project.

Website link : [ Sweet Alert ](https://sweetalert.js.org/)

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/138643473/1927cd97-c8b8-4f16-93b6-394766418a82)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
sure you can add it
