### ISSUE TITLE
Feat: Little Control buttons Tooltip Improvement.

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#317]
### Describe the feature

Currently hovering over "Fast Playback", "Current Speed", and "Slow Playback" all show the same tooltip, "Speed Controls".
The same for "Grid Height" and "Apply" button, that shows "Change Grid Height".

I propose that tooltip shows :
- "Reduce Speed" when we hover over "Slow Playback".
- "Current Speed" when we hover over "Current Speed".
- "Increase Speed" when we hover over  "Fast Playback".
- "Grid Height" when we hover over "Grid Height".
- "Apply Grid Height" when we hover over  "Apply" with a valid grid height.
- "Invalid Grid Height" when we hover over "Apply" with an invalid grid height.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/7b5513d1-cb68-4605-a1d1-db4a116abb3b)
![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/a1d15ed0-58f1-446f-8287-f9195df82ed5)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
You can start working on it
