### ISSUE TITLE
Improving the curser 

### ISSUE THREAD

**Issue by Ramben0909** [EternoSeeker/gameoflife#319]
### Describe the feature

The blue dot will only arrive when the curser is over the grid, and it will not be there when it goes outside of the grid 

### Add ScreenShots

![Screenshot 2024-06-23 200043](https://github.com/EternoSeeker/gameoflife/assets/121795329/84a55d71-e57a-4884-adf3-56cc82b9f566)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Ramben0909** [comment]
I will add the necessary JavaScript and adjust the program accordingly.
Hey @EternoSeeker please add the label and assign me this issue.

**Comment by Ramben0909** [comment]
I have a good knowledge of JavaScript.
Hey @EternoSeeker please add a label and assign me this issue

**Comment by EternoSeeker** [comment]
Alright, you can work on it
