### ISSUE TITLE
Feat:Add a Contact Us Section

### ISSUE THREAD

**Issue by Abhinavpatra** [EternoSeeker/gameoflife#323]
### Describe the feature

Is there an existing issue for this?

- [x]  I have searched the existing issues

below here i will add link to another page that will open a page with details and methods to contact the creator of this website with their social media handles and also a message box with name and emails if necessary 

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/149466436/59a759f8-6d52-4f93-9c3f-348c63df1dc8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Similar issue was worked on before
