### ISSUE TITLE
BUG: Feedback form margins are not proper forms cuts from top and in bottom very less space remain.

### ISSUE THREAD

**Issue by zalabhavy** [EternoSeeker/gameoflife#326]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

I will give proper margin from top and bottom.

![image](https://github.com/EternoSeeker/gameoflife/assets/126322584/5ef8f398-c2a3-4e44-9dba-930ca6fc52fa)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@EternoSeeker Kindly assign and merge my previous PR #318

**Comment by Aradhyajha** [comment]
@EternoSeeker sir... i want to work on this issue can you please assign this task to me

**Comment by zalabhavy** [comment]
@EternoSeeker Please assign this issue to me i will fix it as soon as possible !
