### ISSUE TITLE
BUG: The whole back-up div is interactive in the game rules section but cursor changes only at the up icon

### ISSUE THREAD

**Issue by Rajul-29** [EternoSeeker/gameoflife#327]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The grey area in the back-up div is also interactive but the cursor doesn't indicate that

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Rajul-29** [comment]
Hey @EternoSeeker
I have understood your codebase and would like to work on this.

**Comment by EternoSeeker** [comment]
can you send screenshots

**Comment by Rajul-29** [comment]
![eternoseeker](https://github.com/EternoSeeker/gameoflife/assets/165317476/5d0156eb-fd4a-46fb-851b-53ef120d9e3e)
Webpage link: https://eternalgameoflife.netlify.app/gamerules.html

**Comment by Rajul-29** [comment]
On clicking here the button works but there is no indication that it is interactive

**Comment by bubble003** [comment]
You can work on it @Rajul-29.
