### ISSUE TITLE
BUG: The button images are not visible in game rules page

### ISSUE THREAD

**Issue by CoderGirl2844** [EternoSeeker/gameoflife#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Only the name is displayed instead of the images of the buttons
![Screenshot 2024-06-30 193403](https://github.com/EternoSeeker/gameoflife/assets/155231566/da989a0c-8f1e-4cc5-944a-055a48010f78)
please assign me this issue 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by partha120804** [comment]
:) oh, I deleted those image files

**Comment by Soujanya2004** [comment]
hi, I have been following your project and would love to contribute, please assign me the issue.
