### ISSUE TITLE
Feat: Add social media icons in the sidebar

### ISSUE THREAD

**Issue by JagjeetChauhan** [EternoSeeker/gameoflife#335]
### Describe the feature

You can add social media icons like github. link

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/98844703/3e94e621-ebed-44d5-bf75-77a4dd750536)
You can add links below feedback form

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Yes we can do that, you can work on it
