### ISSUE TITLE
Feat: Adding a FAQ Page

### ISSUE THREAD

**Issue by Ojas-Arora** [EternoSeeker/gameoflife#337]
### Describe the feature

@EternoSeeker I want to add multilanguage facility to the website. Kindy assign this issue to me,

### Add ScreenShots

![Screenshot 2024-06-22 174346](https://github.com/EternoSeeker/gameoflife/assets/127867874/eb562713-169e-4b64-b593-ce2884e10ec3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
I am not sure if it's required for this project, if you have any other ideas do let me know, thank you.

**Comment by Ojas-Arora** [comment]
@EternoSeeker Can I add a FAQ Page to the website.

**Comment by EternoSeeker** [comment]
you can add
