### ISSUE TITLE
Add popular presets like blinker toad and beacon

### ISSUE THREAD

**Issue by Pratik2401** [EternoSeeker/gameoflife#34]
## I'm submitting a ...

- [ ] Feature request

Changing the behavior of Conway's Game of Life enables exploration of new patterns and emergent phenomena, aids in algorithmic experimentation, educational demonstrations, and artistic creations, while also serving as a model for problem-solving and simulating real-world dynamics.

**Comment by Pratik2401** [comment]
plz assign me these issue under GSSOC'24

**Comment by EternoSeeker** [comment]
#8 this issues is being worked on, kindly wait before I merge those presets

**Comment by EternoSeeker** [comment]
@Pratik2401 you can raise a PR if you are done working on it.

**Comment by EternoSeeker** [comment]
@Pratik2401 any updates ?
You can add the presets and raise a PR, thank you
