### ISSUE TITLE
Feat: Music button to be listed under settings with grid and wrap options

### ISSUE THREAD

**Issue by partha120804** [EternoSeeker/gameoflife#347]
### Describe the feature

Add music button within the setting with wrap and grid buttons with a suitable checkbox/slider button design

### Add ScreenShots

<img width="180" alt="image" src="https://github.com/EternoSeeker/gameoflife/assets/138643473/4f34cffb-0a1d-4a5d-9282-5ed92a3ace98">

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
okay
