### ISSUE TITLE
Adding introductory dialogue box 

### ISSUE THREAD

**Issue by Jasleen1210** [EternoSeeker/gameoflife#349]
### Describe the feature

I would like to add a series of pop up boxes that welcomes you to the site and walk you through how to operate the various buttons and where to find buttons for task [classic pop ups that have option of next, skip, and close]

### Add ScreenShots

-

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
that would require a bit work right

**Comment by Jasleen1210** [comment]
Hello! is there any discord server for this repo where contributors can exchange ideas? 

Anyways here is the figma [prototype](https://www.figma.com/design/naSn7MkdN00tVxJp0WY41E/Untitled?node-id=0-1&t=lYAdyuVl3W8h4QGV-1) , I still have to edit the sentence structures and all but this is the structure ill be following:
please let me know any other things you'd like to add/remove from this and whether this matches what you'd like to see in your website.

**Comment by EternoSeeker** [comment]
> Hello! is there any discord server for this repo where contributors can exchange ideas?
> 
> Anyways here is the figma [prototype](https://www.figma.com/design/naSn7MkdN00tVxJp0WY41E/Untitled?node-id=0-1&t=lYAdyuVl3W8h4QGV-1) , I still have to edit the sentence structures and all but this is the structure ill be following: please let me know any other things you'd like to add/remove from this and whether this matches what you'd like to see in your website.

we don't have our own discord server, although this project does have it's own channel in gssoc server,  you can interact there thank you
