### ISSUE TITLE
Adding icons 

### ISSUE THREAD

**Issue by Soumya6Tiwari** [EternoSeeker/gameoflife#350]
### Describe the feature

Adding icons for different sections such as settings , about , feedbacks etc :- on the side navbar . this will enhance ur website.

### Add ScreenShots

![Screenshot 2024-07-05 021832](https://github.com/EternoSeeker/gameoflife/assets/117037441/a48d1e2b-fae8-429a-bea7-1fc4578a127d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Soumya6Tiwari** [comment]
@EternoSeeker  kindly assign me this issue under gssoc'24

**Comment by EternoSeeker** [comment]
alright, you can start working on it
