### ISSUE TITLE
Feat:Make website SEO friendly

### ISSUE THREAD

**Issue by chaanakyaaM** [EternoSeeker/gameoflife#354]
### Describe the feature

I would like to add appropriate meta tags including the content, description, og:property and more for making the website SEO friendly.

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
sure
