### ISSUE TITLE
BUG: Inconsistence use of icon images

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#355]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The icons in the home screen looks like this:
![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/d437b6a2-40cb-4f08-9ae3-d00705f591c8)

While the the icons for those same buttons in the Game-Rules page looks like this:
![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/1e63685c-fcc0-420d-b7a5-bf85128b8efe)

This is possibly the result of ignorance by one or more people. I will make the images consistence.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
you can change the ones in gamerules file
