### ISSUE TITLE
BUG: Gssoc label missing in Readme.md

### ISSUE THREAD

**Issue by ananyag309** [EternoSeeker/gameoflife#357]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Gssoc Label is missing in the readme.md. Can i fix it? I want to enhance overall readme by adding some animations and give propwer aliignment to it. can i add feature in section i will attach the respective ss. please assign this issue to me under gssoc. I will fix the bug and enhance the overall readme.
Bug:
![fiz it](https://github.com/EternoSeeker/gameoflife/assets/145869907/ddc7efee-6006-4047-afe5-00432bbb9602)
can i add something like this - 
![readmee](https://github.com/EternoSeeker/gameoflife/assets/145869907/057b0e4d-0151-41ff-add5-5ed9a351ed2d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
you can work on it
