### ISSUE TITLE
We can Add a Landing Page for this.

### ISSUE THREAD

**Issue by HardCoder404** [EternoSeeker/gameoflife#36]
We can add a landing page for this, where user can go and know more about the gameplay. Also we can add a login and signup functionality for better experience. Also in Sidebar we can add Dashboard Section where all the gameplay will list down with there rules and regulations. 

Assign me this issue. I'll be glad to work on that.

**Comment by Yuvraj960** [comment]
@EternoSeeker Please assign this issue to me
