### ISSUE TITLE
Feat: Addition of about us page.

### ISSUE THREAD

**Issue by HishitaGupta** [EternoSeeker/gameoflife#361]
### Describe the feature

Addition of a visually appealing about us page by taking reference from the readme of the project.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/159264060/90e112a8-12d1-42ed-9f8a-dd7402ef7ecd)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
game rules has the same content as readme file, if you have any ideas related to the project, please tell.
