### ISSUE TITLE
BUG: In small screen not proper margins in buttons

### ISSUE THREAD

**Issue by zalabhavy** [EternoSeeker/gameoflife#363]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

![image](https://github.com/EternoSeeker/gameoflife/assets/126322584/b8f2ee54-94d2-4edf-895c-2de6ff2af46d)

I will fix margins in small screen and make it better.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@EternoSeeker Please assign this task to me ! and also #348 

Thank You !

**Comment by EternoSeeker** [comment]
you can work on it

**Comment by rounakdey6** [comment]
please this work assign this issue
