### ISSUE TITLE
Feat: Enhancing the checkboxes in settings

### ISSUE THREAD

**Issue by partha120804** [EternoSeeker/gameoflife#368]
### Describe the feature

The check boxes can be updated to switches like this

### Add ScreenShots

![pattern-switch](https://github.com/EternoSeeker/gameoflife/assets/138643473/6ed42796-c9b9-4f75-8aff-3a01605787e8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by partha120804** [comment]
self

**Comment by rounakdey6** [comment]
please this assign issue

**Comment by partha120804** [comment]
i am on it
