### ISSUE TITLE
Feat: Better Mobile View

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#370]
### Describe the feature

Currently, in the mobile view, if the width of the settings bar is larger than the width of the mobile screen, the user would have to swipe to close the Settings Menu. Additionally, some minor changes would have to be made in the settings bar to make for a better user experience in mobile.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/145102345/9aa85e87-efa7-4c69-a316-01187ad0ab75)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
sure you can work on it
