### ISSUE TITLE
Feat:Add icon in back button

### ISSUE THREAD

**Issue by heli0707** [EternoSeeker/gameoflife#378]
### Describe the feature

An icon has been added to the back button, replacing the large button with a more compact and visually appealing image. This enhances the user interface by providing a cleaner and more intuitive navigation option.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/b3e70c31-a0e8-47cc-846f-9c9c68361ecf)
replace with 
![image](https://github.com/user-attachments/assets/8e2be20d-f55e-4cfb-8e83-6e76c674412f)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
okay you can work on it
