### ISSUE TITLE
Feat: Emoji Review Addition in feedback section

### ISSUE THREAD

**Issue by Damini2004** [EternoSeeker/gameoflife#379]
### Describe the feature

Emoji Review Addition in feedback section

### Add ScreenShots

![Screenshot 2024-07-13 142538](https://github.com/user-attachments/assets/118dd2a1-9f3c-41ba-abd9-c75a00d54b94)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
please elaborate, you can mention in bit more detail what you are planning to do

**Comment by Damini2004** [comment]
![image](https://github.com/user-attachments/assets/967d0635-c955-4d3d-b030-5f55ef3a2f5a)
like this

**Comment by EternoSeeker** [comment]
there is star rating there already

**Comment by Damini2004** [comment]
@EternoSeeker It will look more tempting as i add this feature recently here 
https://rapidoc.netlify.app/
in feedback section 
Please assign this to me i want to work on it.

**Comment by EternoSeeker** [comment]
alright, you can work on it
