### ISSUE TITLE
Light and Dark modes of the screen

### ISSUE THREAD

**Issue by jennifereunice** [EternoSeeker/gameoflife#383]
## I'm submitting a ...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

**Comment by jennifereunice** [comment]
dark and light mdoes of the screen

**Comment by Abhi00045** [comment]
assign me this issue

**Comment by EternoSeeker** [comment]
> ## I'm submitting a ...
> * [ ]  Bug report
> * [x]  Feature request
> * [ ]  Documentation changes
> * [ ]  Other (please mention)
> 
> ## Current behaviour
> ## What is the motivation / use case for changing the behavior?

there is a black theme available currently. So I think it doesn't need a dark mode seperately
