### ISSUE TITLE
Feat: Design about page

### ISSUE THREAD

**Issue by Ridhima10** [EternoSeeker/gameoflife#392]
### Describe the feature

I would like to add about page for this website. it will be useful for new users to have an insight about the website

### Add ScreenShots

![Screenshot 2024-07-17 213315](https://github.com/user-attachments/assets/65d43b4d-ccb2-4932-8295-2a0727ecb2b8)
Right now its redirecting to readme file but it should have a page for it

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
the gamerules page is same as readme file, so there isn't a requirement for another page, thank you.
