### ISSUE TITLE
BUG:

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#394]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The up/down key just drags the 'Randomness' slider, it doesn't change its value. It just shows that the value has changed, but if we press the 'Random' button, it retains its previous value. The value only really changes when we drag by  mouse.

Uploading Screen Recording 2024-07-19 123848.mp4…

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
the video is not visible

**Comment by VijaySamant4368** [comment]
@EternoSeeker sorry for the mistake
https://github.com/user-attachments/assets/d8d6b6ea-4dec-4484-bb02-aa2406a54ff8

**Comment by VijaySamant4368** [comment]
@EternoSeeker

**Comment by EternoSeeker** [comment]
okay you can work on it

**Comment by VijaySamant4368** [comment]
@EternoSeeker please checkout thi pr.
