### ISSUE TITLE
Feat: adding same animation to sidebar as home page

### ISSUE THREAD

**Issue by dnyandeepchute** [EternoSeeker/gameoflife#395]
### Describe the feature

adding same animation to sidebar as home page

### Add ScreenShots

![Screenshot 2024-07-19 230515](https://github.com/user-attachments/assets/1d218b7a-d7b2-4256-9e28-160e14ff502e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
sure you can work on it
