### ISSUE TITLE
BUG: Old screenshot in Game-rules page

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#396]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The screenshot of game in gamerules.html is old
![image](https://github.com/user-attachments/assets/bf82582d-563c-4052-90c4-f06c028f7e6d)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by bubble003** [comment]
@VijaySamant4368 u can fix this.

**Comment by VijaySamant4368** [comment]
@bubble003 I have sent the PR
