### ISSUE TITLE
BUG: animation not visible due to color  

### ISSUE THREAD

**Issue by dnyandeepchute** [EternoSeeker/gameoflife#398]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

animation not visible due to color  

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by bubble003** [comment]
@dnyandeepchute you can share a screenshot or video that would be better.

**Comment by dnyandeepchute** [comment]
![Screenshot 2024-07-19 230515](https://github.com/user-attachments/assets/5a86d859-273d-48c2-a699-51a08f0499dc)


@bubble003
