### ISSUE TITLE
Feat: Add Contributors Page.

### ISSUE THREAD

**Issue by zalabhavy** [EternoSeeker/gameoflife#399]
### Describe the feature

This Page is for efforts shows efforts of Contributor.

This page contains Contributor card in that profile picture , total contribution and github profile link will be added.

Theme will be matches website.

Demo :- 

![image](https://github.com/user-attachments/assets/6794d9b7-5e2d-4688-8d49-d4034323eec2)

### Add ScreenShots

NA

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by zalabhavy** [comment]
@EternoSeeker Please assign me this task !

Thank You !

**Comment by zalabhavy** [comment]
@EternoSeeker Please assign me this task !

Thank You !

**Comment by EternoSeeker** [comment]
Sure you can work on it
