### ISSUE TITLE
Feat:Adding Social media icons on right side of the page

### ISSUE THREAD

**Issue by Maana-Ajmera** [EternoSeeker/gameoflife#400]
### Describe the feature

I want to add social media icons on right side of the page

### Add ScreenShots

![image](https://github.com/user-attachments/assets/647252b4-9f71-4dd9-8960-3894e5996933)

like this

https://github.com/user-attachments/assets/c2d8a575-48d2-4315-81c6-87f6fa4921b6

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Maana-Ajmera** [comment]
@EternoSeeker Please assign it to me

**Comment by EternoSeeker** [comment]
Yeah, you can work on it
