### ISSUE TITLE
📝[Docs]: Adding Installation and Setup Guide

### ISSUE THREAD

**Issue by iamkanhaiyakumar** [EternoSeeker/gameoflife#403]
### What's wrong with the existing documentation

I've noticed your project lacks a Installation and Setup Guide, crucial for sharing essential project details and fostering collaboration. As a GSSoC 2024 participant, I'm keen on contributing meaningfully. I'm dedicated to crafting a thorough README for the project's benefit. Thanks for considering. Eagerly awaiting your response. I've done many  file for another project, you can check my profile, i always give my best.

You see my work [HERE](https://github.com/singodiyashubham87/Draw-it-out?tab=readme-ov-file#contributing-guidelines)

Can you assign me this task?

Thank u @EternoSeeker 

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
what would you install ?
