### ISSUE TITLE
Re-design and Enhance the scroll to top button

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [EternoSeeker/gameoflife#405]
### Describe the feature

Hey @EternoSeeker and @bubble003 

The current "scroll to top" button can be improved in terms of design and functionality. 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/c6be3889-fe51-4c97-9359-9f3fa8d07aee)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
yes, you can work on it
