### ISSUE TITLE
BUG: The Feedback Form is Not Properly Aligned and Responsive

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [EternoSeeker/gameoflife#412]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Hey @EternoSeeker and @bubble003 

On this website the feedback form is not aligned and the responsiveness

![image](https://github.com/user-attachments/assets/53adbf45-641f-4329-8eaa-a63d7bab48cb)

I would like to fix it like this

![image](https://github.com/user-attachments/assets/474501b8-04ad-4876-a418-bacb6ffd0b73)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by bubble003** [comment]
@RadhikaMalpani1702 👍
