### ISSUE TITLE
game Rule page on the same page

### ISSUE THREAD

**Issue by ankit1576** [EternoSeeker/gameoflife#418]
### Describe the feature

Currently the game rules page is opening in the new tab every time clicked and game is also reloaded making ui bad  ,  WHat we cat do is we can create card to display consise game rules in the same page in the  card and, if user click more details of game play then only redirected to a new tab 

### Add ScreenShots

![image](https://github.com/user-attachments/assets/873c73d6-33fa-44ba-b7b0-275b73df93e6)
![image](https://github.com/user-attachments/assets/f8404c65-4e68-47e5-a399-d3052573b6d4)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ankit1576** [comment]
@EternoSeeker @bubble003 assighn this issue to me

**Comment by EternoSeeker** [comment]
yea that sounds a nice idea, you can work on it. Contribution period is till 10 aug
