### ISSUE TITLE
Feat:Add History Page to the Game

### ISSUE THREAD

**Issue by Nayanika1402** [EternoSeeker/gameoflife#419]
### Describe the feature

The History option is not working so I want to add History.html page to the game.

### Add ScreenShots

![Screenshot 2024-07-27 094901](https://github.com/user-attachments/assets/526bf300-88fc-4855-a14f-066ca1032499)
As you can see that other buttons arre working except the history so it seems a bit odd to the visitors.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
it'll only store history after you first play it. History stores last 5 patterns the user played, in session storage. Did you try testing it out, if there's still any bug, please let me know
