### ISSUE TITLE
Feat: Automated Greeting Workflow

### ISSUE THREAD

**Issue by sanmarg** [EternoSeeker/gameoflife#42]
### Describe the feature

I propose to create a GitHub workflow named "Greetings". This workflow will automatically greet users who create new issues or pull requests in this repository.  The Greeting will look like "Hi there! Thanks for opening this issue. We appreciate your contribution to this open-source project. We aim to respond or assign your issue as soon as possible."

Please assign this issue to me.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/50082154/aaaf6fb3-8890-4c62-8ffe-c9097f3e0674)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Is it necessary ?

**Comment by sanmarg** [comment]
Creating a GitHub workflow named "Greetings" to automatically greet users who create new issues or pull requests in a repository can be beneficial for several reasons:

-    Acknowledgment: It provides immediate acknowledgment to contributors that their contribution is valued and appreciated. 
     This can encourage them to continue contributing to the project in the future.

-   Community Engagement: By greeting contributors automatically, you create a welcoming and friendly atmosphere within 
     your project's community. This can foster a sense of belonging and encourage more engagement from contributors.

-    Efficiency: Automating the greeting process saves time for maintainers, as they don't have to manually greet each 
     contributor. This allows maintainers to focus on other important tasks, such as reviewing code or addressing issues.

-   Consistency: Automating the greeting ensures that every contributor receives the same level of acknowledgment, regardless 
     of the time or workload of the maintainers. This helps maintain a consistent experience for all contributors.

-    Professionalism: Automatic greetings add a level of professionalism to your project by demonstrating that you have 
      established processes in place to interact with contributors promptly and courteously.

**Comment by sanmarg** [comment]
Any  Updates?

**Comment by EternoSeeker** [comment]
@sanmarg sure you can work on it

**Comment by sanmarg** [comment]
Task done.

**Comment by EternoSeeker** [comment]
thank you
