### ISSUE TITLE
BUG: Extra padding on top of sidebar

### ISSUE THREAD

**Issue by haseebzaki-07** [EternoSeeker/gameoflife#433]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

There is extra padding/margin on top of sidebar of the app that is also adding unnecesarry scrollbar for now , it can be fixed.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
you can work on it
