### ISSUE TITLE
Feat: Enhance the Ui of FAQ Page and Scroll to Top Button

### ISSUE THREAD

**Issue by MastanSayyad** [EternoSeeker/gameoflife#435]
### Describe the feature

Hey @EternoSeeker and @bubble003 

I would like to enhance the UI of FAQ PAge and Its functionality 

![image](https://github.com/user-attachments/assets/906137ea-7378-4152-b039-0afcfd44c90b)

![image](https://github.com/user-attachments/assets/faedb8a8-84be-4c6d-8f40-fdc4faf4a355)

Additionally I would like to enhance the button Ui, also vertical scroll bar

![image](https://github.com/user-attachments/assets/5ea44342-ddef-41e8-9ca7-45f8d10fdd7d)

![image](https://github.com/user-attachments/assets/7a3fec9a-edfd-44a3-b7e0-4d8fa0452891)

### Add ScreenShots

N/A

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
yes, you can work on it
