### ISSUE TITLE
Feat: I want to add Contributors Page.

### ISSUE THREAD

**Issue by vishanurag** [EternoSeeker/gameoflife#436]
### Describe the feature

- A Contributors Page will showcase all the amazing contributors of this project.
- Users can see who has worked on this project.

### Add ScreenShots

_The Contributors page will look like this._

![Screenshot 2024-08-03 142749](https://github.com/user-attachments/assets/727e8cef-3621-4b49-9601-a23f4dbbdff3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by vishanurag** [comment]
@EternoSeeker Please assign this issue to me under GSSoC'24

**Comment by EternoSeeker** [comment]
Similar issue is been created before, thank you
