### ISSUE TITLE
Feat:Add new Theme

### ISSUE THREAD

**Issue by jayesh2474** [EternoSeeker/gameoflife#44]
### Describe the feature

Add new them Dark Neon Color
i can add colors like images.
Please assign this issue me to under Gssoc'24 , i would like to work on this

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/115784462/d37a7e04-fcdf-444e-88a9-68dce7576187)
![image](https://github.com/EternoSeeker/gameoflife/assets/115784462/265847e6-f490-4a9a-8cec-4dcb80c0ec21)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Let's see how it goes about the images part

**Comment by ekramzafar** [comment]
I WANT TO DO THIS CAN YOU ASSIGN ME
