### ISSUE TITLE
BUG: Contributors Data is Incomplete in Contributors Page

### ISSUE THREAD

**Issue by RadhikaMalpani1702** [EternoSeeker/gameoflife#441]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

@EternoSeeker and @bubble003 

In contributors page is showing only list of 30 contributors.
Additionaly I would like to design the contributors card.

![image](https://github.com/user-attachments/assets/9f45068a-123d-445c-9f11-afe370e7cd3b)

![image](https://github.com/user-attachments/assets/ae4005bd-fa15-4a20-82bf-23bfa9d24f82)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
yea you can work on it
