### ISSUE TITLE
BUG: Shortcut keys not working

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#442]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The shortcut that were working earlier, are no longer working.
@EternoSeeker please checkout this issue.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
you can work on it
