### ISSUE TITLE
BUG: Button size is weird in gamerules page.

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#443]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

The buttons in the table in the gamerules page are not looking good.
![image](https://github.com/user-attachments/assets/3e75bc0e-0be1-47dd-9726-b10b5024eb68)
@EternoSeeker please check this out.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
you can work on it
