### ISSUE TITLE
Feat: Addition of dark mode in the game's rule page

### ISSUE THREAD

**Issue by VijaySamant4368** [EternoSeeker/gameoflife#444]
### Describe the feature

Addition of a dark theme mode can greatly improve the UI of the page.

### Add ScreenShots

s

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by VijaySamant4368** [comment]
@EternoSeeker please look into this

**Comment by EternoSeeker** [comment]
There's a black theme in the themes already
