### ISSUE TITLE
Feat:changing the color scheme and font

### ISSUE THREAD

**Issue by Agrima11** [EternoSeeker/gameoflife#45]
### Describe the feature

the font can be a bit improved...clear demarkations can be done between the headings and the other texts.
color scheme is monotone but i feel the grid should be in a pale yellow color.
plsss assign this issue to me.
@

### Add ScreenShots

![Screenshot 2024-05-13 112230](https://github.com/EternoSeeker/gameoflife/assets/168272914/6291a793-3b91-4648-b082-fb8a81a8349e)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by ashish027120** [comment]
@EternoSeeker I Am GSSOC' 2024 Contributor .                                                                                                                               Can You Please Assign This Task  To Me ??                                                                                                                                           I Really Want To Work On This Issue .

**Comment by deepanshpandey108** [comment]
good evening sir! kindly assign this task to me
