### ISSUE TITLE
Feat: Dynamic Animation

### ISSUE THREAD

**Issue by Harman8815** [EternoSeeker/gameoflife#47]
### Describe the feature

I plan to enhance the website's appeal by adding animations using JavaScript. This includes animating the entire website to make it more engaging during the loading process. Additionally, I intend to add interactive animations to buttons, making them visually appealing and providing feedback to users when clicked.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harman8815** [comment]
I am very eager to work on it please assign me this issue.

**Comment by EternoSeeker** [comment]
#30 #29

**Comment by EternoSeeker** [comment]
Sure you can work on it

**Comment by Harman8815** [comment]
Okay I will start working on it
