### ISSUE TITLE
Feat: add a menu bar toggle button and some font changes 

### ISSUE THREAD

**Issue by Harman8815** [EternoSeeker/gameoflife#49]
## Description
I have added a responsive menu bar button using the Font Awesome icon library and added the required JavaScript to make it functional. Additionally, I made some changes to the font to make the title more attention-grabbing. This improves the visualization of the website.

## Related Issue
I can make it more appealing by animating the whole website. I can use the AOS library to do so.

## Motivation and Context
My changes make the website a little cleaner by hiding the menu bar when not in need.

### Add ScreenShots

![ScreenShot_20240513141912](https://github.com/EternoSeeker/gameoflife/assets/115714095/9c14bef1-dad0-42d1-9df5-2135e62447e0)
![ScreenShot_20240513141906](https://github.com/EternoSeeker/gameoflife/assets/115714095/bb7a6159-1aa4-43b9-bc7e-6f1edb078d6c)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harman8815** [comment]
please allow me to work on this issue

**Comment by EternoSeeker** [comment]
You can work on it

**Comment by Harman8815** [comment]
Okay, I will start working on it from today.
