### ISSUE TITLE
[Bug] : Cell doesn't Accessable

### ISSUE THREAD

**Issue by sivaprasath2004** [EternoSeeker/gameoflife#52]
### What's wrong with the existing documentation

- If the `.cell` doesn't cursor `pointing` this is not accessble...
- i would like to the cell will be `hovered` then the cursor point to the place can be `clickable`..
- so i'm ready to solve the bug please assign me..

### Add ScreenShots

[Screencast from 2024-05-13 22-10-10.webm](https://github.com/EternoSeeker/gameoflife/assets/121082414/4e80ed96-9d79-43b9-bcfd-13be4f71f3f1)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
you can work on it
