### ISSUE TITLE
Feedback Mechanism: 

### ISSUE THREAD

**Issue by hasmithagunda123** [EternoSeeker/gameoflife#53]
### Describe the feature

Provide a way for users to provide feedback or report issues directly from the application.Feat:

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Please describe further, thank you

**Comment by EternoSeeker** [comment]
@hasmithagunda123 any updates ?

**Comment by adityas-github** [comment]
Please assign this issue to me.As I am GSSoC 2024 contributor.

**Comment by EternoSeeker** [comment]
yes
