### ISSUE TITLE
Contact us section 

### ISSUE THREAD

**Issue by Anamika-Ratna** [EternoSeeker/gameoflife#56]
### Describe the feature

This project misses the contact us section . I would like to add that to it after the "history " part where some of the required details of owner will be mentioned. If you like this idea, kindly assign this issue to me under the Gssoc tag with the details you want under the contact us section.  

### Add ScreenShots

![Screenshot (666)](https://github.com/EternoSeeker/gameoflife/assets/122286548/468fdd22-ecab-4926-895e-59bef7a067d0)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
You can work on it.

**Comment by Siddhant-Mahato** [comment]
Hello @EternoSeeker , 

Can you please assign the task  to me  ?

**Comment by HimangshuRanjan** [comment]
@EternoSeeker, I would like to fix this issue. Please do assign me this.

**Comment by Anamika-Ratna** [comment]
Hi @EternoSeeker, I have made the changes, kindly review them.
Thank you 
#110
