### ISSUE TITLE
[UI] : Adding a Responsive and Functional Footer section

### ISSUE THREAD

**Issue by aditya-bhaumik** [EternoSeeker/gameoflife#57]
## I'm submitting a ...

- [ ] Bug report
- [x] Feature request
- [ ] Documentation changes
- [ ] Other (please mention)

## Current behaviour
The current project lacks a footer section.

## Describe the feature

I will try adding the following changes to the code:
    Add a footer section to the project.
    Include essential links such as About Us, Contact Us, and Privacy Policy.
    Implement responsive design to ensure the footer looks good on all devices.
    Consider including social media icons for easy access to social media profiles.
    Ensure that the footer is visually consistent with the rest of the project, matching the color scheme and style.

## What is the motivation / use case for changing the behavior?
A well-designed footer can improve the overall user experience by offering additional resources and information, thereby increasing user engagement. Could you please assign me this issue under GSSoC'24

## Record 

- [x]  I agree to follow this project's Code of Conduct
- [x]   I'm a GSSOC'24 contributor
- [x]  I want to work on this issue

**Comment by Aashka19** [comment]
please assign it to me

**Comment by Gokilp** [comment]
please assign to me  Gssoc
