### ISSUE TITLE
DOC: Icons not visible in 'Readme' file

### ISSUE THREAD

**Issue by divyalaldinani** [EternoSeeker/gameoflife#58]
### What's wrong with the existing documentation

Icons/buttons are not clearly visible in the readme file.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/82147067/93d139f1-2125-48cb-bcaa-f1e3b210da50)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
How do you plan to solve it, please describe
