### ISSUE TITLE
Feat:Adding hover effect over the elements in the settings section

### ISSUE THREAD

**Issue by souvik-maity** [EternoSeeker/gameoflife#59]
### Describe the feature

Adding hover effect over the elements in the settings section

### Add ScreenShots

![Screenshot 2024-05-14 220324](https://github.com/EternoSeeker/gameoflife/assets/145227417/2b76579d-37df-41d4-9634-3d0adf19f12a)
kindly consider assigning it to me

### Record

- [x] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by souvik-maity** [comment]
kindly consider assigning the issue to me under gssoc'24

**Comment by deepanshpandey108** [comment]
good evening sir! kindly assign this task to me

**Comment by EternoSeeker** [comment]
@souvik-maity sure you can work on it.

**Comment by EternoSeeker** [comment]
@souvik-maity any updates ?

**Comment by souvik-maity** [comment]
@EternoSeeker i have raised the PR .Kindly check and consider merging it
