### ISSUE TITLE
Feat: Ability to change size of Grid

### ISSUE THREAD

**Issue by Dirus007** [EternoSeeker/gameoflife#63]
### Describe the feature

Give users the ability to increase the number of rows and columns i.e. the size of the universe before starting. In case, it is to big to fit on screen. Users should be able to drag/scroll the part of grid they want to see.
This might need effort of some people to implement. 
Would like to hear everyone's thoughts.

### Add ScreenShots

<img width="937" alt="image" src="https://github.com/EternoSeeker/gameoflife/assets/98613736/3cadcf23-7a44-4480-abfe-00fa786a31d9">
Something like this site. 
https://playgameoflife.com/

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by EternoSeeker** [comment]
since the project uses plain html/css/js it may be hard to implement. I had thought about this feature too. You can work on it and take your time. Also keep updating your fork, cause there are other people who will work on same files in that period

**Comment by Dirus007** [comment]
> since the project uses plain html/css/js it may be hard to implement. I had thought about this feature too. You can work on it and take your time. Also keep updating your fork, cause there are other people who will work on same files in that period

Sure, will try my best.

**Comment by TiwariRahul16** [comment]
Hii @EternoSeeker
 I have  added the functionality in which the user can change the size of grid accrording to their preference.
 please assign this task to me.
I am adding screenshot

Before
![before](https://github.com/EternoSeeker/gameoflife/assets/168175850/c1832881-8007-455d-a503-21ecc7fcf1b5)

After
![after](https://github.com/EternoSeeker/gameoflife/assets/168175850/8ace0267-c815-4da2-b240-a71d937e0913)

**Comment by EternoSeeker** [comment]
@Dirus007 any updates ?

**Comment by Dirus007** [comment]
> @Dirus007 any updates ?

Yeah worked on the dragging feature. Refining it, its a little awkward to move sometime. I fixed grid size in code but I think @TiwariRahul16 's idea will also suit me.

**Comment by EternoSeeker** [comment]
@TiwariRahul16 Can you make it look better for mobile as well

**Comment by TiwariRahul16** [comment]
> @TiwariRahul16 Can you make it look better for mobile as well

Done
