### ISSUE TITLE
DOC: Update documentation for the new presets

### ISSUE THREAD

**Issue by EternoSeeker** [EternoSeeker/gameoflife#70]
### What's wrong with the existing documentation

- Add information and gifs regarding the new presets in the README.md file.

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by Ananyarawa8t** [comment]
Hey @EternoSeeker  ,
I would like to help you in making the documentation more user interactive and readable. Kindly assign this issue to me under GSSOC'24 label.
Best Regards,
Ananya Rawat

**Comment by EternoSeeker** [comment]
sure you can work on it

**Comment by EternoSeeker** [comment]
@Ananyarawa8t any updates ?

**Comment by Ananyarawa8t** [comment]
Hey @EternoSeeker I'm working on it, I'll give updates asap.

**Comment by EternoSeeker** [comment]
Hello @Ananyarawa8t Are you still working on it ?
