### ISSUE TITLE
Feat: Workflow for Closing Old Issues

### ISSUE THREAD

**Issue by Asymtode712** [EternoSeeker/gameoflife#71]
### Describe the feature

This feature aims to automate the process of managing old issues, ensuring that the repository remains organized and focused on relevant tasks. By automatically closing old issues, it reduces manual overhead for repository maintainers and helps keep the issue tracker tidy and up-to-date.

### Add ScreenShots

![Annotation 2024-05-17 010432](https://github.com/EternoSeeker/gameoflife/assets/115717746/40db9c69-08ba-4bc7-b496-d28f5d135c50)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Asymtode712** [comment]
@EternoSeeker Please assign me this issue under gssoc'24

**Comment by EternoSeeker** [comment]
Could you please give me more details, thank you.

**Comment by Asymtode712** [comment]
So basically, this workflow is designed to automatically close issues in a repo that have been inactive for more than 30 days. It runs on a daily schedule and performs the following tasks:

- Checks out the repository.
- Retrieves all open issues.
- Checks the last update time of each issue.
- Closes issues that have been inactive for more than 30 days.
- Adds a comment to the closed issues explaining why they were closed.
