### ISSUE TITLE
Add one more preset

### ISSUE THREAD

**Issue by anshulsoni4** [EternoSeeker/gameoflife#76]
### Describe the feature

i want to work on this issue and add another preset for this, that is a areow and heart combo

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/74638335/903a0896-efe7-421e-b414-d4293a192da8)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
Yea I can understand you, but the pattern won't evolve into something interesting
Check these patterns
https://conwaylife.com/wiki/Category:Patterns
Maybe you can add some interesting pattern from those listed there

**Comment by EternoSeeker** [comment]
@anshulsoni4 did you choose any interesting pattern from that list ?
