### ISSUE TITLE
Adding social media icons.

### ISSUE THREAD

**Issue by Dhruv-Gaba** [EternoSeeker/gameoflife#77]
### Describe the feature

Description:
Adding social media icons for GitHub, Twitter, Facebook, LinkedIn, Instagram, and YouTube to the website header and footer.
Icons are visually consistent, responsive, and accessible. Also hover effects would be added to the icons.

### Add ScreenShots

Responsive social media icons along with hover effects(for reference)
![image](https://github.com/EternoSeeker/gameoflife/assets/141745373/99831062-79ba-44a6-9266-161680881e03)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by pulkit49** [comment]
I can help you with that. Please assign me under GSSOC 2024.

**Comment by EternoSeeker** [comment]
#56 the contact us section is added, if you have more ideas please tell
