### ISSUE TITLE
Add PR template 

### ISSUE THREAD

**Issue by suhanipaliwal** [EternoSeeker/gameoflife#78]
I would like to add a pull request template for this repository. I believe that having a standardized template will help streamline the contribution process, ensuring that all necessary information is included and making it easier for maintainers to review and merge pull requests.

Could you please assign this issue to me under GSSOC'24.

**Comment by EternoSeeker** [comment]
A pull request template is already present for the repository, thank you

**Comment by suhanipaliwal** [comment]
I would like to update the template and organise it in a better way.
