### ISSUE TITLE
For Dark Neon Theme the play buttons shown unexpected behaviour .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [EternoSeeker/gameoflife#79]
### Describe the feature

When i switched theme to dark neon then the play button that contains Left arrow ,play button and right arrow are not changing color according to that and showing  some kind of dark black color that makes hard to see these buttons .

### Add ScreenShots

![Screenshot 2024-05-18 091227](https://github.com/EternoSeeker/gameoflife/assets/118350936/867aa155-4b8f-4719-a96a-b1671cd2efb2)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
They use same icons for all themes, you can add icons for neon theme, sure.

**Comment by Ayushmaanagarwal1211** [comment]
Ok
