### ISSUE TITLE
[FEAT]: Add more presets

### ISSUE THREAD

**Issue by EternoSeeker** [EternoSeeker/gameoflife#8]
## I'm submitting a

- [x] Feature request

## Current behaviour

Only 3 presets present

More patterns can be found here:

https://conwaylife.com/wiki/Category:Patterns
You can add some famous ones, with interesting evolution

## What is the motivation/use case for changing the behavior?

Users get to see more presets and how they behave and evolve in conway's game of life

**Comment by Aryan-Shan** [comment]
Hi @EternoSeeker I would like to work on this issue please assign it to me

**Comment by EternoSeeker** [comment]
Do share which presets will you add. If you require help then feel free to reach out.

**Comment by Aryan-Shan** [comment]
i am intending to add Pulsar, B29, Fireship and spider presets.

I have cloned your repo and tried running it locally on a live server , there seems to be some problem with the website ,loading the presets and changing the theme. Can you please tell me is it faced by you too or its just an individual issue?

thanks

**Comment by EternoSeeker** [comment]
Maybe you can try sharing screenshots. I am not sure what the problem is

**Comment by EternoSeeker** [comment]
> @EternoSeeker i am intending to add Pulsar, B29, Fireship and spider presets.
> 
> I have cloned your repo and tried running it locally on a live server , there seems to be some problem with the website ,loading the presets and changing the theme. Can you please tell me is it faced by you too or its just an individual issue?
> 
> thanks

The presets seem good, let's see how it goes

**Comment by Aryan-Shan** [comment]
@EternoSeeker  I have resolved the issues i stated earlier actually there was an error with the file path in the original code. Also there was a mismatched SHA384 hash which i corrected.

I have added new Presets as well. please allow me to push a new branch so that you can review the changes

**Comment by Aryan-Shan** [comment]
Please review and merge the pull request
