### ISSUE TITLE
Feat: Add a cursor pointer when hover on theme color text .

### ISSUE THREAD

**Issue by Ayushmaanagarwal1211** [EternoSeeker/gameoflife#80]
### Describe the feature

According to me when hovering on theme color like Red then the cursor changed to be like pointer but it remains arrow and changing to pointer at some random position .

### Add ScreenShots

https://github.com/EternoSeeker/gameoflife/assets/118350936/cd451552-1eb2-4b8e-a38d-ea26deb8a46d

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
sure you can work on it
