### ISSUE TITLE
Feat:Add new pattern to presets

### ISSUE THREAD

**Issue by YadlaMani** [EternoSeeker/gameoflife#82]
### Describe the feature

adding a star pattern to the presets

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/133841094/1a164dae-131c-4382-82df-ed988d5e550e)
![image](https://github.com/EternoSeeker/gameoflife/assets/133841094/85ec9ce7-5d9c-46d5-a053-5917dff14418)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
How does it evolve ?

**Comment by YadlaMani** [comment]
@EternoSeeker  sry i didn't fully understood the code i can't implement this issue will be closing the issue now
