### ISSUE TITLE
Dark Theme & Share Button

### ISSUE THREAD

**Issue by prafulnigam** [EternoSeeker/gameoflife#9]
I can work over a Dark Theme Addition & Share Button for the Website.

I am Praful Nigam. Under GSSOC'24, I would like to work on this issue. Pls assign me this!!

**Comment by EternoSeeker** [comment]
Sure

**Comment by prafulnigam** [comment]
Thank You !

**Comment by psychic-coder** [comment]
Hello I am Rohit Ganguly , can you please allow me to contribute to this project under GSSOC'24.

**Comment by satyaveni299** [comment]
I can work over a Dark Theme Addition & Share Button for the Website.Pls assign me this!!
