### ISSUE TITLE
Feat: Adding Animations on Loading and Scrolling

### ISSUE THREAD

**Issue by MHusain22** [EternoSeeker/gameoflife#91]
### Describe the feature

Animations will make the UI of the website more enhanced.
Using vanilla CSS and animations library can be implemented.

### Add ScreenShots

I can Add animations to the Page on loading and scrolling just like in my portfolio website https://mhportfolio.vercel.app/. Please assign me this to add new feature.
also I have added animations to this website in opensource contribution of GSSOC.
https://github.com/EternoSeeker/gameoflife/assets/118285713/bee87c79-5ccb-47d8-904c-83c056aac583

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
@MHusain22 you can work on it

**Comment by MHusain22** [comment]
@EternoSeeker  I have added the animations and created a pull request please review it and let me know if any changes.
