### ISSUE TITLE
Feat: To make settings section into a responsive sidebar menu

### ISSUE THREAD

**Issue by VedaVarxha** [EternoSeeker/gameoflife#92]
### Describe the feature

I wish to make the settings section into a sidebar which is collapsible and expandable. @EternoSeeker Please assign it to me so that I can start working on it.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
it is collapsable, although you can make some styling changes, so that it's consistent for small screen sizes @VedaVarxha

**Comment by VedaVarxha** [comment]
@EternoSeeker Thank you for assigning this issue. I am working on it
