### ISSUE TITLE
Background Theme Switching is not working. Only Gradient theme is working.

### ISSUE THREAD

**Issue by Janani-m17** [EternoSeeker/gameoflife#93]
### Describe the feature

While clicking different theme radio buttons it will to switch to the corresponding background color.
Hover is not working properly for radio buttons

### Add ScreenShots

![WhatsApp Image 2024-05-20 at 15 26 02_efb79260](https://github.com/EternoSeeker/gameoflife/assets/124059957/9c503ab2-62c7-485b-8cdd-6da74750a463)
In this while clicking various radio button like red, blue the background is not switching.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

@EternoSeeker

**Comment by EternoSeeker** [comment]
can you explain it more clearly, thank you

**Comment by Janani-m17** [comment]
Thank you for your reply sir. The issue i raised was when i click button such as red, blue in the side bar to change the theme, It is not working. Only the gradient theme is working. By resolving this issue, user can experience wide range of themes. Please assign this issue to me.
@EternoSeeker

**Comment by EternoSeeker** [comment]
@Janani-m17 you can work on it.
also, do you mean that after the gradient theme, the normal themes are not getting switched I think?
Could you send a screen recording if possible, it'll be helpful to understand what issue you are facing, thank you.

**Comment by Janani-m17** [comment]
Thank you assigning this issue to me sir. The exact issue is if the user choose the theme from colors such as red, blue it is working fine both the background and grid color are changing. But if the user chooses the gradient theme at first and then switch to colors only the grid color is changing, background remains static.

https://github.com/EternoSeeker/gameoflife/assets/124059957/63242541-e06d-425d-975d-f413dc8b8ea4
