### ISSUE TITLE
Feat: Login and SignUp Page is not working.

### ISSUE THREAD

**Issue by GnanariddhikaRavikumar** [EternoSeeker/gameoflife#94]
### Describe the feature

The login and signup button in home page is not responding. After registering the user is unable to login. The actions are not handled properly.  There by defining the actions properly the user can experience the smooth functioning of app.

### Add ScreenShots

![image](https://github.com/EternoSeeker/gameoflife/assets/125359008/013c1ab4-e3d4-45ac-9f5d-58fd32f6025b)
Login Button is not working
Sign Up button is not handled properly.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

@Ghanshyam89

**Comment by syma-parween** [comment]
I want to work on this issue

**Comment by EternoSeeker** [comment]
#10 there is an existing issue, I'll let you know if they aren't working on it

**Comment by Gokilp** [comment]
please assign to me
