### ISSUE TITLE
BUG: Unexpected Symbol or Marker near the theme selection menu option

### ISSUE THREAD

**Issue by karthickkumarsm** [EternoSeeker/gameoflife#96]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

Unexpected Symbol or Marker near the theme selection menu option has been detected.Image is given as proof
![Screenshot 2024-05-20 200716](https://github.com/EternoSeeker/gameoflife/assets/89688112/56bc6147-eb4d-40ba-abed-27385b5ea355)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by EternoSeeker** [comment]
sure, you can work on it

**Comment by karthickkumarsm** [comment]
![image](https://github.com/EternoSeeker/gameoflife/assets/89688112/ab8045c5-5834-4a94-b95c-60a4939fcf6c)
have a look is it ok now?
