### ISSUE TITLE
Feat:Two hamburger icon is showing in mobile view but desktop showing one and hamburger not working properly in mobile

### ISSUE THREAD

**Issue by kapilG0** [EternoSeeker/gameoflife#97]
### Describe the feature

Two hamburger icon is showing in mobile view 

### Add ScreenShots

![Screenshot_20240520_221452](https://github.com/EternoSeeker/gameoflife/assets/59639410/5b323008-9cc9-437a-a6dc-03f1aae88c66)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by kapilG0** [comment]
Hello @EternoSeeker please assign this issue to me under gssoc 24

**Comment by EternoSeeker** [comment]
yes you can fix it for mobile @kapilG0

**Comment by TiwariRahul16** [comment]
Hi @EternoSeeker 
can you assign me please
I've figured out this problem.

**Comment by EternoSeeker** [comment]
@kapilG0 any updates ?

**Comment by kapilG0** [comment]
> @kapilG0 any updates ?

Hello @EternoSeeker https://github.com/EternoSeeker/gameoflife/pull/118 this pr i have raised for this issue please check
